#ifndef __Qt4All__
#define __Qt4All__

// Qt Toolkit
#include <Qt/qglobal.h>
#include <QtCore/qeventloop.h>
#include <QtCore/qfile.h>
#include <QtCore/QMutex>
#include <QtCore/qnamespace.h>
#include <QtCore/qrect.h>
#include <QtCore/qregexp.h>
#include <QtCore/QSet>
#include <QtCore/QSignalMapper>
#include <QtCore/QTemporaryFile>
#include <QtCore/qtextcodec.h>
#include <QtCore/qtextstream.h>
#include <QtCore/qthread.h>
#include <QtCore/qtimer.h>
#include <QtCore/qtranslator.h>
#include <QtCore/QUrl>
#include <QtCore/qvariant.h>
#include <QtCore/QWaitCondition>
#include <QtGui/qaction.h>
#include <QtGui/QActionGroup>
#include <QtGui/qapplication.h>
#include <QtGui/qcheckbox.h>
#include <QtGui/qclipboard.h>
#include <QtGui/qcolordialog.h>
#include <QtGui/qcombobox.h>
#include <QtGui/qcursor.h>
#include <QtGui/QDesktopWidget.h> 
#include <QtGui/QDockWidget>
#include <QtGui/qdrawutil.h>
#include <QtGui/qevent.h>
#include <QtDesigner/QFormBuilder>
#include <QtGui/QFileDialog>
#include <QtGui/qfontdatabase.h>
#include <QtGui/qfontdialog.h>
#include <QtGui/qimage.h>
#include <QtGui/QImageWriter>
#include <QtGui/qinputdialog.h>
#include <QtGui/qlabel.h>
#include <QtGui/qlayout.h>
#include <QtGui/qlineedit.h>
#include <QtGui/QListWidget>
#include <QtGui/QMainWindow>
#include <QtGui/qmenubar.h>
#include <QtGui/qmessagebox.h>
#include <QtGui/qmime.h>
#include <QtGui/qmovie.h>
#include <QtGui/qpainter.h>
#include <QtGui/qpalette.h>
#include <QtGui/qpixmap.h>
#include <QtGui/qprinter.h>
#include <QtGui/QProgressBar>
#include <QtGui/qpushbutton.h>
#include <QtGui/qradiobutton.h>
#include <QtGui/qscrollbar.h>
#include <QtGui/qslider.h>
#include <QtGui/qspinbox.h>
#include <QtGui/qsplashscreen.h>
#include <QtGui/qsplitter.h>
#include <QtGui/qstatusbar.h>
#include <QtGui/qstyle.h>
#include <QtGui/qstylefactory.h>
#include <QtGui/QSyntaxHighlighter>
#include <QtGui/qtabbar.h>
#include <QtGui/qtabwidget.h>
#include <QtGui/QTextBrowser>
#include <QtGui/QTextDocument>
#include <QtGui/QTextEdit>
#include <QtGui/QToolBar>
#include <QtGui/qtoolbox.h>
#include <QtGui/qtoolbutton.h>
#include <QtGui/qtooltip.h>
#include <QtGui/qvalidator.h>
#include <QtGui/QWhatsThisClickedEvent>
#include <QtGui/qwidget.h>
#include <QtGui/qworkspace.h>
#include <QtNetwork/QFtp>
#include <QtNetwork/QHttp>
#include <QtNetwork/QHttpResponseHeader>
#include <QtNetwork/QHttpRequestHeader>
#include <QtNetwork/QTcpServer>
#include <QtNetwork/QTcpSocket>
#include <QtOpenGl/qgl.h>

#endif