#ifndef __Qt4All__
#define __Qt4All__

// Qt Toolkit
// QtCore
#include <qglobal.h>
#include <qeventloop.h>
#include <qfile.h>
#include <QMutex>
#include <qnamespace.h>
#include <QPointer>
#include <QProcess>
#include <qrect.h>
#include <qregexp.h>
#include <QSet>
#include <QSignalMapper>
#include <QTemporaryFile>
#include <qtextcodec.h>
#include <qtextstream.h>
#include <qthread.h>
#include <qtimer.h>
#include <qtranslator.h>
#include <QUrl>
#include <qvariant.h>
#include <QWaitCondition>
// QtGui
#include <QAbstractItemModel>
#include <QAbstractTextDocumentLayout>
#include <qaction.h>
#include <QActionGroup>
#include <qapplication.h>
#include <QBitmap>
#include <qcheckbox.h>
#include <qclipboard.h>
#include <qcolordialog.h>
#include <qcombobox.h>
#include <qcursor.h>
#if QT_VERSION >= 0x040200
#include <QDesktopServices>
#endif
#include <QDesktopWidget> 
#include <QDockWidget>
#include <qdrawutil.h>
#include <qevent.h>
#include <QFileDialog>
#include <QFileIconProvider>
#include <qfontdatabase.h>
#include <qfontdialog.h>
#include <QGroupBox>
#include <QHeaderView>
#include <qimage.h>
#include <QImageWriter>
#include <qinputdialog.h>
#include <QItemDelegate>
#include <QItemEditorFactory>
#include <qlabel.h>
#include <qlayout.h>
#include <qlineedit.h>
#include <QListWidget>
#include <QMainWindow>
#include <qmenubar.h>
#include <qmessagebox.h>
#include <qmime.h>
#include <qmovie.h>
#include <qpainter.h>
#include <qpalette.h>
#include <qpixmap.h>
#include <QPixmapCache>
#include <QPrinter>
#include <QPrintDialog>
#include <QProgressBar>
#include <qpushbutton.h>
#include <qradiobutton.h>
#include <QScrollArea>
#include <qscrollbar.h>
#include <QSettings>
#include <QShortcut>
#include <qslider.h>
#include <qspinbox.h>
#include <qsplashscreen.h>
#include <qsplitter.h>
#include <qstatusbar.h>
#include <qstyle.h>
#include <qstylefactory.h>
#include <QStyleOptionButton>
#include <QStylePainter>
#include <QSyntaxHighlighter>
#include <qtabbar.h>
#include <qtabwidget.h>
#include <QTextBrowser>
#include <QTextDocument>
#include <QTextDocumentFragment>
#include <QTextEdit>
#include <QToolBar>
#include <qtoolbox.h>
#include <qtoolbutton.h>
#include <qtooltip.h>
#include <QTreeView>
#include <QTreeWidget>
#include <qvalidator.h>
#include <QWhatsThis>
#include <QWhatsThisClickedEvent>
#include <qwidget.h>
#include <qworkspace.h>
// QtNetwork
#include <QFtp>
#include <QHttp>
#include <QHttpResponseHeader>
#include <QHttpRequestHeader>
#include <QTcpServer>
#include <QTcpSocket>
// QtOpenGL
#include <qgl.h>
// QtSvg
#include <QSvgRenderer>
#include <QSvgWidget>
// QtUiTools
#include <QUiLoader>
#include <QtDesigner/QFormBuilder>


#endif
