/* XPM */
static const char *curv_info[]={
"22 22 11 1",
"a c #000000",
"g c #0000ff",
"f c #008080",
"c c #008000",
"d c #00ffff",
"# c #808080",
". c None",
"e c #ff0000",
"h c #ffaa00",
"b c #000000",
"k c #ffff00",
"......................",
"......................",
".......#aaaa#.........",
".bb...aa....aa........",
".bcb.a#ddd...#a...eee.",
".bcc#add......a#..eee.",
"..bcacd........a..hhh.",
"..bcacdb.......a..hhh.",
"..bcacccb......a..kkk.",
"..bcaccccb...d.a..kkk.",
"..bc#accccb.d.a#..ccc.",
"...bca#ccccdd#a...ccc.",
"...bccaaccccaaaa..fff.",
"...bccc#aaaa#.aaa.fff.",
"...bccccccccbb.aa.ddd.",
"....bccccbbb....a.ddd.",
"....bcbbb.........ggg.",
".....bb...........ggg.",
"......................",
"......................",
"......................",
"......................"};
/* XPM */
//"c c #84ad84",
static const char *import_mesh[]={
"22 22 6 1",
". c None",
"# c #000000",
"c c #ffff00",
"a c #808080",
"b c #c0c0c0",
"f c #008000",
".............##.......",
".............###......",
".............#f##.....",
".............#ff##....",
"...####....#.#fff##...",
"..#....##.##.#ffff##..",
".........###.#fffff##.",
"........####.#ffffff##",
".......#####.#########",
".####.................",
"#abab##########.......",
"#babababababab#.......",
"#ababababababa#.......",
"#babab################",
"#abab##cccccccccccc##.",
"#bab##cccccccccccc##..",
"#ab##cccccccccccc##...",
"#b##cccccccccccc##....",
"###cccccccccccc##.....",
"##cccccccccccc##......",
"###############.......",
"......................"};

static const char *export_mesh[]={
"22 22 6 1",
". c None",
"# c #000000",
"c c #ffff00",
"a c #808080",
"b c #c0c0c0",
"f c #008000",
".............##.......",
".............###......",
".............#f##.....",
".#....####...#ff##....",
".##.##....#..#fff##...",
".###.........#ffff##..",
".####........#fffff##.",
".#####.......#ffffff##",
".............#########",
".####.................",
"#abab##########.......",
"#babababababab#.......",
"#ababababababa#.......",
"#babab################",
"#abab##cccccccccccc##.",
"#bab##cccccccccccc##..",
"#ab##cccccccccccc##...",
"#b##cccccccccccc##....",
"###cccccccccccc##.....",
"##cccccccccccc##......",
"###############.......",
"......................"};
/* XPM */
static const char *solid_mesh[]={
"22 22 4 1",
"# c #000000",
"a c #00ff00",
". c None",
"b c #ffffff",
".........#####........",
".......##aaaaa##......",
".....##aaaaaaaaa##....",
"....#aaaaaaaaaaaaa#...",
"...#aaaaaaaaaaaaaaa#..",
"...#aaabbbaaaaaaaaa#..",
"..#aaabbbbbaaaaaaaaa#.",
"..#aaabbbbbaaaaaaaaa#.",
".#aaaabbbbbaaaaaaaaaa#",
".#aaaaabbbaaaaaaaaaaa#",
".#aaaaaaaaaaaaaaaaaaa#",
".#aaaaaaaaaaaaaaaaaaa#",
".#aaaaaaaaaaaaaaaaaaa#",
"..#aaaaaaaaaaaaaaaaa#.",
"..#aaaaaaaaaaaaaaaaa#.",
"...#aaaaaaaaaaaaaaa#..",
"...#aaaaaaaaaaaaaaa#..",
"....#aaaaaaaaaaaaa#...",
".....##aaaaaaaaa##....",
".......##aaaaa##......",
".........#####........",
"......................"};
