/* XPM */
static const char *pCopy[]={
"24 24 25 1",
"w c None",
"q c None",
"o c None",
"v c None",
"r c None",
"u c None",
"t c None",
"e c None",
"b c None",
"a c None",
". c None",
"f c None",
"c c None",
"i c None",
"k c None",
"# c None",
"h c #000000",
"p c #0000ff",
"l c #003094",
"s c #0030ce",
"m c #2965ff",
"d c #7b7d7b",
"n c #cecbce",
"j c #ffff94",
"g c #ffffff",
"................########",
"aabbbbbbbbbbbbbc########",
"##ddddddddddeeef########",
"##dggggggggdheeeeeei####",
"##dggggggjgdgheeeeeek###",
"##dggggjggjdggheeeeee###",
"##dgglllddddddddddeee###",
"##dgggggdggggggggdheee##",
"##dggllldggggggggdgheeee",
"##dgjgjgdggggggjgdggheee",
"##dggllldggmmmmgjhhhhhee",
"##dgjggjdgggjggjgjnnnhee",
"##dggllldggmmmmmmmmgnhee",
"##dgggjgdggjgjgjgjgjnhoe",
"##dgjllldgjppppppppgnhee",
"##dggjgjdggjgjgjgjgjnhqe",
"##dnnnnndgjppppppppgnhee",
"##hhhhhhdggggjgjgjgjnhre",
"##eeeeeedgjssssssssgnhee",
"##eeeeeedggjgjgjgjgjnhoe",
"##eeeeeednnnnnnnnnnnnhee",
"##tttttrhhhhhhhhhhhhhhre",
"##uuuuvuvuvuruququququtt",
"####################ruwu"};


/* XPM */
static const char *pCut[]={
"24 24 39 1",
"h c None",
"G c None",
"C c None",
"F c None",
"t c None",
"E c None",
"g c None",
"n c None",
"y c None",
"x c None",
"D c None",
"s c None",
"J c None",
"k c None",
"B c None",
"q c None",
"K c None",
"p c None",
"H c None",
"f c None",
"b c None",
"a c None",
". c None",
"m c None",
"e c #000000",
"A c #0000ff",
"z c #003063",
"w c #0096ff",
"r c #2965ff",
"v c #29cbff",
"d c #7b7d7b",
"l c #848684",
"u c #94ffff",
"I c #adaead",
"i c #adb2ad",
"o c #cecbce",
"c c #cecfe7",
"# c #e7e3ef",
"j c #ffffff",
".......................#",
"aaaaaaaaaaaaaaaaaaaaaaaa",
"bbbbbcdeffffffffddffbbbb",
"fffghdieffffffffdjefffff",
"ffgkhgjleffffffdjlefffff",
"ffgmnfdoeffffffdoeffffff",
"fffgpfdjleffffdjleffffff",
"fffgmffdoeffffdoefffffff",
"ffffgffdjleffdjlefffffff",
"ffffgfffdoeffdoeffffffff",
"ffffffffdjledjleffffffff",
"fffffffffdoedoefffffffff",
"fffffffffdjlelefffffffff",
"ffffffffffdoeeffffffffff",
"ffffffffffdoiefffffqffff",
"fffffffrrroierrrrrsfffff",
"fffftfruvvwecrvuvwexffff",
"ffftyruzzAwecruzzAweBfBf",
"fftyCrvzcAwecrvzcAwefDff",
"fftECrwAAAwecrwAAAwexfff",
"fftFGfAwwwefffAwwwexffff",
"fffGFHHeeeHHBHIeeeBHffff",
"HHHHhhhHHBHJhhhBHBHHHHHH",
"KKKKKKJKJKsKBKJKJKxKKKKK"};


/* XPM */
static const char *pFCIcon[]={
"16 16 4 1",
"# c #000000",
"a c #848284",
"b c #ff0000",
". c #ffffff",
"........#.......",
".......##aaaaaa.",
"........#.....a.",
".#######......a.",
".##...........a.",
".##...bbbb....a.",
".##..bb..bb...a.",
".###bb#...b..###",
".##.bb........#.",
".##.bb..........",
".##.bb..........",
".##.bb..........",
".##.bb....b.....",
".....bb..bb.....",
"......bbbb......",
"................"};


/* XPM */
static const char *pFlight[]={
"24 24 26 1",
"a c None",
"# c None",
"b c None",
"s c None",
"m c None",
"k c None",
"x c None",
"n c None",
"l c None",
"w c None",
"u c None",
"v c None",
"t c None",
"r c None",
"q c None",
"p c None",
". c None",
"c c None",
"e c #000000",
"i c #009ea5",
"j c #0800ff",
"d c #181052",
"f c #4ae7ff",
"o c #adaead",
"h c #cecfe7",
"g c #ffffff",
"........................",
"........................",
"...##..a................",
"...abaacc...............",
"...dd..e................",
"...efeegg...............",
"..eeeggdd.....ee........",
"..eggddh.....efgd.......",
"..eddffd.....efgd.......",
"...effffd...effgd.......",
"...efffffddefffgd.......",
"....eeffffffiiigd.......",
"......eefffffffijd......",
".......eifiiffffjggd...k",
".......effffiggffjjjd.l.",
"......effffggdeeggfffd.m",
".....effgggdd.m.eeeggdm.",
"....effggddn.l.n...edo..",
"pp.egggdd.l.l.l.m.l.l.mp",
"qq.dddd..n.k.l.l.n.l.nql",
"rrrrrrsrlrtrkrurursrtrmr",
"vvvnvuvuvnvvvvvvvvvkvvvv",
"wwmwkwuwwwwwwwwwwwwwwwww",
"xxxxxxxxxxxxxxxxxxxxxxxx"};


/* XPM */
static const char *pFunction[]={
"24 24 15 1",
"g c None",
"j c None",
"h c None",
"m c None",
"l c None",
"k c None",
"c c None",
"b c None",
". c None",
"d c None",
"# c None",
"a c None",
"e c #000000",
"i c #9c9e9c",
"f c #cecfe7",
"...#aaaaa...............",
"bbbaaaaaaaaaaaabbbbbbbbb",
"cccccccdaaaaaccccccccccc",
"cccccccccccccccccccccccc",
"cccccccceeeeecccccccccaa",
"ccccccceeecceeccccccccaa",
"cccccceeecccccccccccccaa",
"cccccceeccccccccccccccaa",
"ccccceeeccccccccccccccaa",
"ccccceecccccccccccccccaa",
"ccccceecccccccccccccccaa",
"ccceeeeeeccceecccceeccaa",
"cceeeeeeccceefccccfeecaa",
"ccccceeccceefeecceefeeaa",
"ccccceeccceecceeeecceeaa",
"ccccceeccceeccfeefgceeaa",
"ccccceeccceecceeeecceeaa",
"ccccceeccceefeecceefeeaa",
"ccccceeccceefgcccccfeeaa",
"cccceecchcieecgcccgeecaa",
"cceeeccjcgcjeecgcjeecjaa",
"kkkkkkkkkkgkkkkkgkhkgkgk",
"lllllllllglllllglllgljll",
"mmmmmmmmgmmmmmgmgmhmgmmm"};


/* XPM */
static const char *pNew[]={
"24 24 15 1",
"f c None",
"h c None",
"i c None",
"m c None",
"g c None",
"l c None",
"k c None",
"j c None",
"# c None",
". c None",
"a c None",
"d c #000000",
"b c #7b7d7b",
"e c #cecbce",
"c c #ffffff",
"........................",
"########################",
"##aaaaaaaaaaaaaaaaa#####",
"##abbbbbbbbbbbbb########",
"##abcccccccccccbd#######",
"##abcccccccccccbcd######",
"##abcccccccccccbccd#####",
"##abcccccccccccddddd####",
"##abcccccccccccceeed####",
"##abcccccccccccccced####",
"##abcccccccccccccced####",
"##abcccccccccccccced####",
"##abcccccccccccccced#f##",
"##abccccccccccccccedg#g#",
"##abcccccccccccccced#g##",
"##abccccccccccccccedg#g#",
"##abcccccccccccccced#g##",
"##abccccccccccccccedg#h#",
"##abcccccccccccccced#i##",
"##abccccccccccccccedg#g#",
"jjabeeeeeeeeeeeeeeedjhjj",
"kkkdddddddddddddddddhkkk",
"lllllglililililililhllll",
"mmmmgmimimimimimimhmmmmm"};


/* XPM */
static const char *pOpen[]={
"24 24 18 1",
"l c None",
"j c None",
"p c None",
"i c None",
"k c None",
"h c None",
"o c None",
"n c None",
"m c None",
"a c None",
"# c None",
". c None",
"b c None",
"d c #000000",
"c c #636500",
"f c #cecfe7",
"g c #ffcb00",
"e c #ffff94",
"........................",
"########################",
"aaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaa",
"aabbbbbbbbbbbbbbbbbbbaaa",
"aaaaacccccaaaaadddaaaaaa",
"aaaaceeeeedaaadaaadfdaaa",
"aaaceeeeeeedaafaaafddaaa",
"aaccccccccccccccdfdddaaa",
"aaceeeeeeeeeeeeedaaaaaaa",
"aaceeeeeeeeeeeeedaaaaaaa",
"aaceeeccccccccccccccdaaa",
"aaceeecgggggggggggggdaaa",
"aaceecgggggggggggggdaaaa",
"aaceecgggggggggggggdaaaa",
"aacecgggggggggggggdahaai",
"aacecgggggggggggggdjaaja",
"aaccgggggggggggggdjajkal",
"aaccgggggggggggggdakaaja",
"aadddddddddddddddajajiaj",
"aaaaaahajaiaiaiaiaiaiala",
"mmmmmhmimimimimimimimmmm",
"nnnnjnininininininlnnnnn",
"ooolopopojojojojopoooooo"};


/* XPM */
static const char *pPaste[]={
"24 24 27 1",
"o c None",
"p c None",
"v c None",
"m c None",
"y c None",
"n c None",
"x c None",
"s c None",
"w c None",
"u c None",
"t c None",
". c None",
"# c None",
"b c #000000",
"q c #0000ff",
"h c #636500",
"c c #636529",
"l c #7b7d7b",
"f c #946500",
"i c #949663",
"a c #ce9600",
"k c #cecb94",
"r c #cecbce",
"g c #ffcb29",
"e c #ffff94",
"j c #ffffce",
"d c #ffffff",
"........................",
".###################....",
".###################....",
".#.....aaaaab...........",
".#.ccccadeefbbbbb.......",
".#cdddaeghhefbiiib......",
".#cdjaaaaaaaafbiib......",
".#cdjbbbbbbbbbbihb......",
".#cjjjkkkkiiiiihhb......",
".#cjjkkikiiihihhhb......",
".#cjkkikiiiiihhhhb......",
".#cjkkkiiillllllll....m.",
".#ckkkiiiilddddddlb..n.o",
".#ckkiiiihldddddeldb..p.",
".#ckiiihihldqqqedbbbbo.m",
".#ciiiiihhldedededrrb.p.",
".#ciiihhhhldqqqqqqqrbp.o",
".#.bbbbbbbldededederb.m.",
".#........ldqqqqqqqrbs..",
"tt.......nlrrrrrrrrrbtot",
"uu....v.n.bbbbbbbbbbbouu",
"wwwwvwvwvwmwnwnwnwnwowww",
"xxxxxxxxxmxnxnxnxnxoxxxx",
"yyyyyyyyyyyyyyyyyyyyyyyy"};


/* XPM */
static const char *pPrint[]={
"24 24 27 1",
"y c None",
"v c None",
"t c None",
"s c None",
"p c None",
"o c None",
"q c None",
"x c None",
"w c None",
"b c None",
"a c None",
"# c None",
". c None",
"g c None",
"f c #000000",
"h c #2965ff",
"m c #299600",
"n c #29cb00",
"k c #636500",
"c c #7b7d7b",
"r c #949629",
"j c #949663",
"u c #a5a2a5",
"d c #cecb94",
"i c #cecfe7",
"l c #ffffce",
"e c #ffffff",
"........................",
"########################",
"aaaaaaaaaaaaaaaaaaaaaaaa",
"bbbbbbbbbcccccccccccbbbb",
"bbbbbbbbcdeeeeeeeedfbbgg",
"bbbbbbbcdehhhhhhhefbbbgg",
"bbbbbbbceeeeeeeeedfbbbgg",
"bbbbbbcdehhhhhhhefibbbgg",
"bbbbbbceeeeeeeeedffffbgg",
"bbbbbcdehhhhhhhefjjfjfgg",
"bbbbbceeeeeeeeeefjfjffgg",
"bbbkkkkkkkkkkkkkkfjfjfgg",
"bbkeeeelllllllldkjfjjfgg",
"bbkkkkkkkkkkkkkkkfjjjfgg",
"bbkeeelllllldddjjfjjfbgg",
"bbkeeldddddmnnmjjfjffogg",
"bbkeldddddddjjjjjffkfbgg",
"bbffffffffffffffffkkfpgg",
"bbbklldddjdjjjjjfkkfqbgg",
"bbbkllddrdjjjjjjfkfsbtgg",
"bbbiffffffffffffffubvbgg",
"bbbbgggggggggggggggggggg",
"wwwwwwwvwqwowowowswtwtwt",
"xxxxxxvxoxpxpxpxtxtxtxyx"};


/* XPM */
static const char *pRedo[]={
"24 24 21 1",
"j c None",
"l c None",
"n c None",
"h c None",
"i c None",
"s c None",
"k c None",
"m c None",
"r c None",
"q c None",
"p c None",
"o c None",
". c None",
"# c None",
"b c #000000",
"a c #299663",
"d c #29cb94",
"c c #29ff94",
"e c #cecfe7",
"f c #ceff94",
"g c #ffffff",
"........................",
"........................",
"........................",
"..##################....",
"..##################....",
"..#...aaaaa.............",
"..#..bcccccaa...........",
"..#.bdcddddccaa.....a...",
"..#bdcdbbbbddcca...ba...",
"..#bdca....bbdccaebfa...",
"..#bdca......bdccbfga...",
"..#bdca.......bdcfgfa...",
"..#bdca.......ebdcfga...",
"..#bdca.......bdcccfa...",
"..#.bdca.....bddddddah..",
"..#.bdca....bbbbbbbbb.i.",
"..#..bdca...j.i.h.h.ii.k",
".....bdca..h.h.h.h.l..m.",
"......bbb.h.n.......hk..",
"oooooohonooooojonononooo",
"pppppjpipppppkpkpkpkpppp",
"qqqqnqnqqqqqqqqqqqqqqqqq",
"rrrrrkrrrrrrrrrrrrrrrrrr",
"ssssssssssssssssssssssss"};


/* XPM */
static const char *pSave[]={
"24 24 19 1",
"l c None",
"n c None",
"o c None",
"m c None",
"q c None",
"c c None",
"b c None",
"a c None",
"# c None",
". c None",
"h c None",
"d c #000000",
"i c #000010",
"k c #101439",
"j c #181839",
"g c #84aede",
"e c #b5b200",
"p c #cecbe7",
"f c #ffffff",
"........................",
"########################",
"aaaaaaaaaaaaaaaaaaaaaaaa",
"bbbcddddddddddddddddcbbb",
"cccddedffffffffffdfddccc",
"cccdeedfggggggggfdffdhhc",
"cccdeedffffffffffddddhhc",
"cccdeedfggggggggfdeedhhc",
"cccdeedffffffffffdeedhhc",
"cccdeedfggggggggfdeedhhc",
"cccdeedffffffffffdeedhhc",
"cccdeedffffffffffdeedhhc",
"cccdeeeddddddddddeeedhhc",
"cccdeeeeeeeeeeeeeeeedhhc",
"cccdeeeeeeeeeeeeeeeedhhc",
"cccdeeedddddddijkdeedhhl",
"cccdeeedddddddfffdeedhhc",
"cccdeeedddddddfffdeedhhm",
"cccdeeedddddddfffdeedhhc",
"cccddeedddddddfffdeddhhm",
"ccccddddddddddddddddnhhc",
"ccccchhhhhhhhhhhhhhhhhho",
"ccccchhhhhhhhhhhhhhhhhhc",
"pqqqqqqqqnqnqlqlqlqlqlqn"};


/* XPM */
static const char *tool_color[]={
"16 15 11 1",
"# c #000000",
"e c #0000ff",
"h c #008284",
"d c #00ff00",
"f c #00ffff",
"g c #840000",
"i c #848284",
". c #c6c3c6",
"a c #ff0000",
"c c #ff00ff",
"b c #ffff00",
"................",
".#############..",
".#aaa#bbb#ccc#..",
".#aaa#bbb#ccc#..",
".#aaa#bbb#ccc#..",
".#############..",
".#ddd#eee#fff#..",
".#ddd#eee#fff#..",
".#ddd#eee#fff#..",
".#############..",
".#ggg#hhh#bbi#..",
".#ggg#hhh#bbi#..",
".#ggg#hhh#bbi#..",
".#############..",
"................"};


/* XPM */
static const char *tool_delete[]={
"16 15 6 1",
"b c #000000",
"d c #008200",
"# c #848284",
"a c #c6c3c6",
". c #ff0000",
"c c #ffff00",
"....####........",
"..##a#####......",
"##aa#baaac##....",
"#aa##b#aaacc##..",
"#aa##b##aaaa#ab.",
"#aaaa###aaaa##b.",
".#aaaddcaca###b.",
".#aadaadda####b.",
".#adddadda###b..",
".#aadaaaaa###b..",
"..#adadada###b..",
"..#aadddda###b..",
"..bbaadaaa##b...",
"....bbaaa###b...",
"......bbaa##b..."};


/* XPM */
static const char *tool_material[]={
"16 15 3 1",
". c #c6c3c6",
"a c #ff0000",
"# c #ffff00",
"................",
".......######...",
"......#......#..",
".....#........#.",
".....##......#..",
"....a.#######a..",
"....aa#aaaaaaa..",
"aaaaaaa#aaaaaa..",
"aaaaaaa#aaaaaa..",
"....aa#aaaaaaa..",
"....a.#######a..",
".....##......#..",
".....#........#.",
"......#......#..",
".......######..."};


/* XPM */
static const char *tool_shading[]={
"16 15 3 1",
"# c #848284",
". c #c6c3c6",
"a c #ffff00",
"................",
".....######.....",
"....#aaaaaa#....",
"...#aaaaaaaa#...",
"...##aaaaaa##...",
"...#a######a#...",
"...#aaaaaaaa#...",
"...#aaaaaaaa#...",
"...#aaaaaaaa#...",
"...#aaaaaaaa#...",
"...#aaaaaaaa#...",
"...#aaaaaaaa#...",
"...#aaaaaaaa#...",
"....#aaaaaa#....",
".....######....."};


/* XPM */
static const char *tool_transparency[]={
"16 15 3 1",
"# c #848284",
". c #c6c3c6",
"a c #ffff00",
"................",
".....######.....",
"....#a.a.a.#....",
"...#a.a.a.aa#...",
"...##a.a.a.##...",
"...#a######.#...",
"...#.a.a.a.a#...",
"...#a.a.a.a.#...",
"...#.a.a.a.a#...",
"...#a.a.a.a.#...",
"...#.######a#...",
"...##a.a.a.##...",
"...#a.a.a.a.#...",
"....#a.a.a.#....",
".....######....."};


/* XPM */
static const char *tool_wireframe[]={
"16 15 3 1",
". c #c6c3c6",
"# c #ffff00",
"a c #ffffff",
"................",
".....######.....",
"....#......#....",
"...#........#...",
"...##......#a...",
"...#.######.a...",
"...#........a...",
"...#........a...",
"...#........a...",
"...#........a...",
"...#.######.a...",
"...##......#a...",
"...#........#...",
"....#......#....",
".....######....."};


/* XPM */
static const char *pUndo[]={
"24 24 22 1",
"m c None",
"k c None",
"o c None",
"i c None",
"h c None",
"t c None",
"j c None",
"s c None",
"l c None",
"r c None",
"q c None",
"p c None",
". c None",
"# c None",
"c c #000000",
"a c #299663",
"d c #29cb94",
"b c #29ff94",
"n c #adaead",
"f c #cecfe7",
"e c #ceff94",
"g c #ffffff",
"........................",
"........................",
"........................",
"...##################...",
".............aaaaa......",
"...........aabbbbbc.....",
"...a.....aabbddddbdc....",
"...ac...abbddccccdbdc...",
"...aecfabbdcc....abdc...",
"...agecbbdc......abdc...",
"...aegebdc.......abdc...",
"...agebdcf.......abdc...",
"...aebbbdc.......abdc...",
"...addddddc.....abdc.h.i",
"...ccccccccc....abdc..i.",
"............j..abdc.hi.i",
"...........i...abdck....",
"..........l.m.nccc...o.i",
".f....o.h.h.m.......o.i.",
"pppppkpopopopippppphpmpp",
"qqqqjqjqjqjqjqqqiqiqjqqq",
"rrrrrrrrrrrrrrrkrorrrrrr",
"ssssssssssssssjsjsssssss",
"tttttttttttttttttttttttt"};


/* XPM */
static const char *view_axo[]={
"20 20 4 1",
"# c #000000",
"a c #00ffff",
". c #c6c3c6",
"b c #ffff00",
"....................",
"....................",
".........##.........",
"........#.a##.......",
".......#..a..##.....",
"......#...a....##...",
".....##...a....##...",
".....#.##.a...#.#...",
".....#...##..#..#...",
"..b..#...aa##...#...",
".bbb.#bba..a#...#...",
"..b..#ba....#aa.#...",
"..b..#a.....#..a#...",
"..b.b##.....#..#....",
"..bb...##...#.#.....",
"...bbbbb.##.##......",
"......bb...##.......",
".....bbb............",
"....................",
"...................."};


/* XPM */
static const char *view_back[]={
"16 16 5 1",
". c None",
"c c #00ffff",
"a c #840000",
"b c #848284",
"# c #ffff00",
".............#..",
"............#...",
"...........#....",
"....aaaaaaaaaa..",
"...ba.#..#..ba..",
"..b.a.#.#..b.a..",
".bbbab##bbb..a..",
".b..a.####b..a..",
".b..a.....b..a..",
".b..a.....b..a..",
".b..a.....b..a..",
".b..a.....b..a..",
".b..aaaaaaaaaa..",
".b.c......b.b...",
".bc.......bb....",
".bbbbbbbbbb....."};


/* XPM */
static const char *view_bottom[]={
"16 16 5 1",
". c None",
"a c #00ffff",
"b c #840000",
"# c #848284",
"c c #ffff00",
"....##########..",
"...#a.......##..",
"..#.a......#.#..",
".##########..#..",
".#..a.....#..#..",
".#..a.....#..#..",
".#..a.....#..#..",
".#..a.....#..#..",
".#..a.....#..#..",
".#..bbbbbbbbbb..",
".#.b...c..#.b...",
".#b...ccc.bb....",
".bbbbbbbbbb.....",
".....c.c.c......",
".......c........",
".......c........"};


/* XPM */
static const char *view_comp_off[]={
"16 16 3 1",
". c None",
"# c #000000",
"a c #848284",
"................",
"................",
".....#########..",
"....#a......##..",
"...#.a.....#.#..",
"..#########..#..",
"..#..a....#..#..",
"..#..a....#..#..",
"..#..a....#..#..",
"..#..a....#..#..",
"..#..aaaaa#aa#..",
"..#.a.....#.#...",
"..#a......##....",
"..#########.....",
"................",
"................"};


/* XPM */
static const char *view_comp_on[]={
"16 16 2 1",
". c None",
"# c #000000",
"................",
"................",
".....#########..",
"....#.......##..",
"...#.......#.#..",
"..#########..#..",
"..#.......#..#..",
"..#.......#..#..",
"..#.......#..#..",
"..#.......#..#..",
"..#.......#..#..",
"..#.......#.#...",
"..#.......##....",
"..#########.....",
"................",
"................"};


/* XPM */
static const char *view_fitall[]={
"16 16 5 1",
"# c None",
"b c #000000",
"c c #848200",
"a c #848284",
". c #ffff00",
"...##########...",
"..#####aaaaa##..",
".#.###a#####a.#.",
"###.#a#######a##",
"####aa#######aa#",
"####a#########a#",
"####a#########a#",
"####aa#######aa#",
"#####a#######a##",
"#####ab#####a###",
"####bb#aaaaa####",
"###bb###########",
"##cb########.###",
".ac##########.#.",
"..############..",
"...##########..."};


/* XPM */
static const char *view_fitarea[]={
"16 16 4 1",
". c None",
"b c #000000",
"a c #848284",
"# c #ffff00",
".#..............",
"###aaaa.aaaaaab.",
".#.....a....a.a.",
".a....a......aa.",
".a...aa......aa.",
".a...a........a.",
".a...a........a.",
".a...aa......aa.",
".a....a......aa.",
".a....ab....a.a.",
".a...bb.aaaa..a.",
"....bb........a.",
"...bb.........a.",
"..bb..........#.",
"..a...aaaaaaa###",
"..............#."};


/* XPM */
static const char *view_front[]={
"16 16 5 1",
". c None",
"a c #00ffff",
"b c #840000",
"# c #848284",
"c c #ffff00",
"................",
"................",
"....##########..",
"...#a.......##..",
"..#.a......#.#..",
".bbbbbbbbbb..#..",
".b..a.....b..#..",
".b..a.....b..#..",
".b..a.....b..#..",
".b..ccc...b..#..",
".b...cc...b..#..",
".b..c.caaabaa#..",
".b.c......b.#...",
".bc.......b#....",
".cbbbbbbbbb.....",
"................"};


/* XPM */
static const char *view_glpan[]={
"16 16 4 1",
". c None",
"b c #000000",
"a c #848284",
"# c #ffff00",
"................",
".......#........",
"......###.......",
".....#.#.#......",
".......#........",
"....aaa#.aaa....",
"..#.a..#...a#...",
".#..a......a.#..",
"######....#####.",
".#..a......a.#..",
"..#.a..#...a#...",
"....baa#.aaa....",
".......#........",
".....#.#.#......",
"......###.......",
".......#........"};


/* XPM */
static const char *view_left[]={
"16 16 5 1",
". c None",
"c c #00ffff",
"# c #840000",
"a c #848284",
"b c #ffff00",
"................",
"................",
"......#aaaaaaaaa",
".....##.......aa",
"....#.#......a.a",
"...#aa#aaaaaa..a",
"..b#..#.....a..a",
"...#b.#.....a..a",
"bbb#bb#.....a..a",
"...#b.#.....a..a",
"..b#..#.....a..a",
"...#..#cccccacca",
"...#.#......a.a.",
"...##.......aa..",
"...#aaaaaaaaa...",
"................"};


/* XPM */
static const char *view_pan[]={
"16 16 2 1",
". c None",
"# c #ffff00",
".......#........",
"......###.......",
".....#.#.#......",
".......#........",
".......#........",
"..#....#....#...",
".#...........#..",
"#####.....#####.",
".#...........#..",
"..#.........#...",
".......#........",
".......#........",
".....#.#.#......",
"......###.......",
".......#........",
"................"};


/* XPM */
static const char *view_reset[]={
"16 16 3 1",
". c None",
"# c #000000",
"a c #ffff00",
"................",
".........#......",
"........###.###.",
".........#...##.",
".........#..#.#.",
".........#.#....",
".........##..#..",
"..........#####.",
"..aaa........#..",
".aa.aa..........",
".aa.aa..........",
".aa.aa..........",
".aa.aa..........",
"..aaa...........",
"................",
"................"};


/* XPM */
static const char *view_right[]={
"16 16 6 1",
". c None",
"d c #000000",
"b c #00ffff",
"a c #840000",
"# c #848284",
"c c #ffff00",
"................",
"................",
"...#########a...",
"..#b.......aa...",
".#.b......a.a...",
"#########a..c...",
"#..b.....a.ca...",
"#..b.....acccccc",
"#..b.....a.ca...",
"#..b.....a..c...",
"#..b.....a..a...",
"#..bbbbbbdbba...",
"#.b......a.a....",
"#b.......aa.....",
"#########a......",
"................"};


/* XPM */
static const char *view_rotate[]={
"16 16 4 1",
". c None",
"a c #000000",
"# c #848284",
"b c #ffff00",
"....#...........",
"...##...........",
"..#a###.........",
"..a###.a##......",
"bbb..##.#.##...b",
".....#...#.a.bbb",
"....#....#..#...",
"....#...b.#.#...",
"....#bb...###...",
"..bbb#....##....",
"bb...##..#a#....",
".......####.....",
".........##.....",
"......b..#......",
".....bbb#.......",
"......b........."};


/* XPM */
static const char *view_top[]={
"16 16 5 1",
". c None",
"b c #00ffff",
"a c #840000",
"c c #848284",
"# c #ffff00",
".......#........",
".......#........",
".....#.#.#......",
"....aa###aaaaa..",
"...ab..#....ac..",
"..a.b......a.c..",
".aaaaaaaaaa..c..",
".c..b.....c..c..",
".c..b.....c..c..",
".c..b.....c..c..",
".c..b.....c..c..",
".c..b.....c..c..",
".c..bbbbbbcbbc..",
".c.b......c.c...",
".cb.......cc....",
".cccccccccc....."};


/* XPM */
static const char *view_zoom[]={
"16 16 5 1",
". c None",
"c c #000000",
"b c #848200",
"# c #848284",
"a c #ffff00",
"................",
"......#####.....",
"aaa..#.....#....",
"....#.......#...",
"....#.......##..",
"...#..aa.....#..",
"...#....aaa..#..",
"...##.......b#..",
"....#.......#...",
"....#c.....#..a.",
"...cc.#####..aaa",
"..cc..........a.",
".cc.............",
"cc..............",
"#...............",
"................"};


/* XPM */
static const char *WhatsThis[]={
"24 24 21 1",
"# c None",
"b c None",
"h c None",
"m c None",
"s c None",
"i c None",
"l c None",
"r c None",
"j c None",
"q c None",
"p c None",
"o c None",
"n c None",
". c None",
"a c None",
"g c #009ea5",
"d c #181052",
"e c #399ea5",
"k c #a5a2a5",
"c c #cecfe7",
"f c #ffff94",
".........##.............",
"..aaaaaaabbaaaaaaaaaaa..",
"..aaaaaaaaaaaaaaaaaaaa.c",
".............dddddd....c",
"..edd....cccdddddddd....",
"..edfd....cddddggdddd...",
"..edffd....dddg...dddg..",
"..edfffd...dddg...dddg..",
"..edffffd...ggg..ddddg..",
"..edfffffd.....cddddg...",
"..edffffffd....ddddg....",
"..edfffffffd..ddddg.....",
"..edffffffffdcdddg.....h",
"..edfffffddd..dddg....h.",
"..edffdffdc..hcggg...i..",
"..edfdedffd.h.dddg..h.j.",
"...edeedffdk.jdddg.l.m.h",
".......edffdj.dddg....j.",
"nn.....edffd.j.ggg...hnn",
"oo....i.edd.j.j.h.h.h.oo",
"pppppiplplpippphphpppppp",
"qqqqqqqqhqjqqqjqmqqqqqqq",
"rrrrrrrrrrrrrrrrrrrrrrrr",
"ssssssssssssssssssssssss"};


