/* XPM */
static const char *px[]={
"24 24 2 1",
"# c #000000",
". c #ffffff",
"........................",
"........................",
"...##..............##...",
"..####............####..",
"..#####..........#####..",
"..######........#####...",
"...######......######...",
"....######....######....",
".....######..######.....",
"......############......",
".......##########.......",
"........########........",
".........######.........",
"........########........",
".......##########.......",
"......############......",
".....######..######.....",
"....######....######....",
"..#######......######...",
".#######........######..",
".######..........#####..",
"..####.............##...",
"........................",
"........................"};

/* XPM */
static const char *App_Parameter[]={
"17 16 2 1",
"# c #000000",
". c #ffffff",
".................",
".................",
"..........##.....",
".#######..##.....",
".##....##..#.....",
".##....##..#.....",
".##....##..####..",
".##....##..#.##..",
".#######...#.....",
".##........#.....",
".##........####..",
".##........#.##..",
".##........#.....",
"...........#.....",
"...........####..",
"................."};

/* XPM */
static const char *CommandLine[]={
"16 16 4 1",
"a c #000000",
"# c #0000ff",
". c #848284",
"b c #ffffff",
"................",
".##############.",
".##############.",
".aaaaaaaaaaaaaa.",
".aaaaaaaaaaaaaa.",
".abaaabaaaaaaaa.",
".aabaaabaaaaaaa.",
".aaabaaabaaaaaa.",
".aaaabaaabaaaaa.",
".aaabaaabaaaaaa.",
".aabaaabaaaaaaa.",
".abaaabaaaaaaaa.",
".aaaaaaaaaaaaaa.",
".aaaaaaaaaaaaaa.",
".aaaaaaaaaaaaaa.",
"................"};

/* XPM */
static const char *Copy[]={
"22 22 69 2",
".# c None",
"Qt c None",
".d c #000000",
"#c c #202020",
".c c #232323",
".j c #2b2b2b",
".b c #2d2d2d",
".a c #343434",
".r c #3a3a3a",
".i c #3c3c3c",
".e c #444444",
".J c #4d4d4d",
".C c #4e4e4e",
".y c #515151",
".s c #595959",
".9 c #808080",
".6 c #919191",
".x c #959595",
"#. c #969696",
".q c #979797",
".1 c #999999",
".X c #9f9f9f",
".w c #a1a1a1",
"#a c #a6a6a6",
".T c #a9a9a9",
".7 c #ababab",
"## c #acacac",
".4 c #afafaf",
".8 c #b0b0b0",
".G c #b1b1b1",
".2 c #b4b4b4",
".E c #bababa",
".Z c #bebebe",
".A c #bfbfbf",
".D c #c0c0c0",
".F c #c2c2c2",
".V c #c3c3c3",
".N c #c7c7c7",
".v c #c8c8c8",
".P c #c9c9c9",
"#b c #cacaca",
".I c #cbcbcb",
".p c #cecece",
".h c #d2d2d2",
".Y c #d3d3d3",
".S c #d6d6d6",
".z c #d7d7d7",
".5 c #d8d8d8",
".U c #d9d9d9",
".K c #dcdcdc",
".3 c #dddddd",
".O c #dfdfdf",
".t c #e1e1e1",
".0 c #e2e2e2",
".L c #e4e4e4",
".W c #e7e7e7",
".R c #e9e9e9",
".u c #eaeaea",
".Q c #ececec",
".l c #ededed",
".k c #eeeeee",
".m c #efefef",
".M c #f1f1f1",
".n c #f3f3f3",
".H c #f4f4f4",
".o c #f5f5f5",
".B c #f8f8f8",
".g c #fcfcfc",
".f c #fdfdfd",
"QtQtQtQtQtQt.#.#.#.#.#.#.#.#.#.#.#.#.#QtQtQt",
"QtQtQtQtQtQt.#.a.b.b.b.b.b.b.c.d.e.#.#.#QtQt",
"QtQtQtQtQtQt.#.b.f.g.g.g.g.g.h.d.d.i.#.#.#Qt",
"Qt.#.#.#.#.#.#.j.k.l.k.m.n.o.p.d.q.d.r.#.#.#",
"Qt.#.a.b.b.b.b.b.b.c.d.s.t.u.v.d.w.x.d.r.#.#",
"Qt.#.b.f.g.g.g.g.g.h.d.d.y.z.A.d.d.d.d.d.#.#",
"Qt.#.b.B.B.B.B.B.B.p.d.q.d.C.D.E.D.F.G.d.#.#",
"Qt.#.b.H.n.n.n.n.n.I.d.w.x.d.J.p.K.L.p.d.#.#",
"Qt.#.b.M.m.m.m.m.m.N.d.d.d.d.d.E.p.O.P.d.#.#",
"Qt.#.b.Q.R.R.R.R.R.S.F.F.F.G.d.T.F.U.V.d.#.#",
"Qt.#.b.W.L.L.L.L.L.L.L.L.L.p.d.X.E.Y.Z.d.#.#",
"Qt.#.b.0.O.O.O.O.O.O.O.O.O.P.d.1.2.p.E.d.#.#",
"Qt.#.b.3.U.U.U.U.U.U.U.U.U.V.d.x.4.N.2.d.#.#",
"Qt.#.b.5.Y.Y.Y.Y.Y.Y.Y.Y.Y.Z.d.6.7.V.8.d.#.#",
"Qt.#.b.Y.p.p.p.p.p.p.p.p.p.E.d.9#.###a.d.#.#",
"Qt.#.b.p.N.N.N.N.N.N.N.N.N.2.d.d.d.d.d.d.#.#",
"Qt.#.b#b.V.V.V.V.V.V.V.V.V.8.d.d.#.#.#.#.#.#",
"Qt.##c.Z###################a.d.#.#.#.#.#.#.#",
"Qt.#.d.d.d.d.d.d.d.d.d.d.d.d.d.#.#.#.#.#.#.#",
"Qt.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#QtQtQtQtQt",
"Qt.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#QtQtQtQtQt",
"Qt.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#QtQtQtQtQt"};

/* XPM */
static const char *customize[]={
"16 16 6 1",
"c c #008000",
"a c #008080",
"d c #00ff00",
"# c #808080",
"b c #c0c0c0",
". c #d4d0c8",
"................",
".##############a",
".#bb##bb##bb##b.",
".#bb##bb##bb##b.",
".##############a",
"................",
"................",
".######aa.......",
".#bbbb#a#a......",
".######.aaa.....",
".######...acc...",
".######....ddc..",
".######....cddc.",
".#bbbb#.....cddc",
".######......ccc",
"................"};

/* XPM */
static const char *Cut[]={
"22 22 33 1",
"# c None",
". c None",
"a c #000000",
"l c #434343",
"k c #646464",
"j c #666666",
"r c #676767",
"o c #787878",
"x c #7b7b7b",
"n c #7d7d7d",
"t c #949494",
"i c #9d9d9d",
"s c #9e9e9e",
"v c #a5a5a5",
"p c #a6a6a6",
"w c #afafaf",
"y c #b0b0b0",
"f c #b2b2b2",
"h c #b3b3b3",
"z c #c1c1c1",
"u c #c2c2c2",
"e c #c4c4c4",
"D c #c5c5c5",
"E c #c7c7c7",
"A c #cbcbcb",
"C c #cecece",
"B c #d3d3d3",
"g c #d4d4d4",
"d c #d5d5d5",
"q c #d6d6d6",
"c c #dcdcdc",
"m c #dedede",
"b c #dfdfdf",
"......................",
"...######.............",
"..##aaa###....########",
".##aaaaa###..#aaaaaaa#",
".#aaaaaa###.#abcdefa##",
".#aa##aa####abcghia###",
".#aa##aaa##abcghia####",
".#aaa##aajabcghia#####",
".##aaaaakabcghia#####.",
".###aaalabcghia#####..",
"..###aaamnohiaa####...",
"...##aapqorsaa####....",
"...##aaatuvaswa###....",
"..##aaaaaxaayzAa###...",
".##aa##aaa##aABBa###..",
".#aa##aaa####aBgBa###.",
".#aa##aa######aBgBa###",
".#aaaaaa#######aCDEa##",
".#aaaaaa###.####aaaaa#",
".##aaaa####..#########",
".##########...########",
"..########.....#######"};

/* XPM */
static const char *FCBackground[]={
"32 32 2 1",
". c None",
"# c #c0c0c0",
"................................",
"................................",
"................................",
"................................",
".......######...####............",
".......#.......#....#...........",
".......#......#.................",
".......#......#.................",
".......#####..#.................",
".......#......#.................",
".......#......#.................",
".......#.......#....#...........",
".......#........####............",
"................................",
"................................",
"................................",
"................................",
"................................",
"........####..........#.........",
".......#....#.......###.........",
".......#....#.........#.........",
".......#....#.........#.........",
".......#....#.........#.........",
".......#....#.........#.........",
".......#....#.........#.........",
".......#....#...#.....#.........",
"........####....#...#####.......",
"................................",
"................................",
"................................",
"................................",
"................................"};

/* XPM */
static const char *FCIcon[]={
"16 16 4 1",
". c None",
"# c #000000",
"a c #848284",
"b c #ff0000",
"........#.......",
".......##aaaaaa.",
"........#.....a.",
".#######......a.",
".##...........a.",
".##...bbbb....a.",
".##..bb..bb...a.",
".###bb#...b..###",
".##.bb........#.",
".##.bb..........",
".##.bb..........",
".##.bb..........",
".##.bb....b.....",
".....bb..bb.....",
"......bbbb......",
"................"};

/* XPM */
static const char *Flight[]={
"24 24 9 1",
". c None",
"a c #000000",
"e c #009ea5",
"f c #0800ff",
"# c #181052",
"b c #4ae7ff",
"g c #adaead",
"d c #cecfe7",
"c c #ffffff",
"........................",
"........................",
"........................",
"........................",
"...##..a................",
"...abaacc...............",
"..aaacc##.....aa........",
"..acc##d.....abc#.......",
"..a##bb#.....abc#.......",
"...abbbb#...abbc#.......",
"...abbbbb##abbbc#.......",
"....aabbbbbbeeec#.......",
"......aabbbbbbbef#......",
".......aebeebbbbfcc#....",
".......abbbbeccbbfff#...",
"......abbbbcc#aaccbbb#..",
".....abbccc##...aaacc#..",
"....abbcc##........a#g..",
"...accc##...............",
"...####.................",
"........................",
"........................",
"........................",
"........................"};

/* XPM */
static const char *form[]={
"32 32 53 1",
"l c #429cff",
"m c #4a9cf7",
"j c #4aa5ff",
"k c #529cf7",
"f c #52a5f7",
"i c #52a5ff",
"h c #52adff",
"c c #5aa5f7",
"e c #5aa5ff",
"d c #5aadff",
"g c #5ab5ff",
"a c #63adf7",
"b c #63adff",
"# c #63b5ff",
". c #6bb5ef",
"u c #9cc6e7",
"t c #9ccef7",
"n c #a5ceef",
"r c #a5cef7",
"s c #a5ceff",
"q c #a5d6ff",
"p c #add6ff",
"o c #addeff",
"Y c #b5bdbd",
"W c #bdbdbd",
"V c #bdc6bd",
"S c #bdc6c6",
"T c #c6c6c6",
"R c #c6cec6",
"Q c #c6cece",
"U c #cecece",
"O c #ced6ce",
"N c #ced6d6",
"X c #ceded6",
"M c #d6ded6",
"K c #d6dede",
"P c #d6e7de",
"C c #dee7de",
"I c #dee7e7",
"J c #deefe7",
"v c #e7efe7",
"H c #e7efef",
"D c #e7f7ef",
"L c #efefef",
"B c #eff7ef",
"G c #eff7f7",
"F c #effff7",
"A c #f7f7ef",
"z c #f7ffef",
"y c #f7fff7",
"E c #f7ffff",
"x c #fffff7",
"w c #ffffff",
".#a#a#ababababcbcdcdcdcecececefa",
"agdgdddddddhdhdhdidiiiiiiijjjjjk",
".gddddddddddhedihiiiiiiiijiiiijc",
"ciihihjijjjjjjjjjjjjjjljljlllllm",
"nopqpqpqqpqrprqrsrrtrrrtrtrttttu",
"vwxxxxxxxyxyyxzyzyyzyAzABABABAvC",
"DEFEFFFFFFFFFBFBGBDBDDDDDHDvvvBI",
"HyFyFyFGFBGGBGDGBDGDHDHDHDvHHHJC",
"HFFFGFGFGGBGBGBGDDDDDHDHvHHJvJHK",
"vFyGFGFBFGDGDDDDBDLDHDHvDJvHJvJK",
"IFGFBFBGGBGBDGDBHDDHDvDHvHHJHJHM",
"CGFGGGGBDGDDDBDDDDHHHDvJHJJvJvJN",
"KFGBGDBGDDBGDDHHHHDvvvHvJvHJJIvO",
"KFBGDGDDBDDDHDDDDvHDHJvHJJJvIJJO",
"MFGDBDGDDBHDDHHvHDJvJHJJvvIJJIIK",
"NGDDGDDDDHDHHDvDHvHJHvJvJIJIIIJM",
"MGDBDDLDHDHDvHvvJHJvJJvIJJIJCJCN",
"CDBDLDDHHDvDHvHHvJvHJIJJIIJIICJN",
"KDHDDHHDHvHHJHvJJvJIvJJIIJCICIIO",
"KBDHHDvHvDvJHJJHvJIJJIIIJCICIPCQ",
"MDHDvHDvHJHJvJvJJIJIIJCJCICIPCJR",
"NDvHDJvHJvJvJvJIJJIJCJICIPIPIPIS",
"OHDvJvHJvJHJJIvJIIJCIICICIPCPPCT",
"UDHJHHJvJvJIvJIICICICCICPPPCPCPN",
"QHJvJJJJJIJIIIJIJICICIPPICPKPKPO",
"RDJvJvIvIJIJJCICCIPIPPIPKPCPKPKQ",
"VHvJIJJIJIJCIJCIICCPIPCPCKPKPKPQ",
"QvJIJIIJIJCIICPIPPICPCPKPKPKPKPT",
"MJIJIJCICICICPIPCIPPKPKPKPKPMKPV",
"NIJICJIJCICPICPIPPCPPKPKPKMKMKPW",
"UJJCIICCIPICPICPCKPKPPKPKKPMKMPW",
"RICPPPPKPPKPKMKMKMKMMMMMMXXNXXKY"};

/* XPM */
static const char *Function[]={
"24 24 4 1",
". c None",
"# c #000000",
"b c #9c9e9c",
"a c #cecfe7",
"........................",
"........................",
"........................",
"........................",
"........#####...........",
".......###..##..........",
"......###...............",
"......##................",
".....###................",
".....##.................",
".....##.................",
"...######...##....##....",
"..######...##a....a##...",
".....##...##a##..##a##..",
".....##...##..####..##..",
".....##...##..a##a..##..",
".....##...##..####..##..",
".....##...##a##..##a##..",
".....##...##a......a##..",
"....##....b##......##...",
"..###.......##....##....",
"........................",
"........................",
"........................"};

/* XPM */
static const char *Import_Box[]={
"16 16 2 1",
". c None",
"# c #ffff00",
".......#........",
"......###.......",
".....#.#.#......",
".......#........",
".......#........",
"..#....#....#...",
".#...........#..",
"#####.....#####.",
".#...........#..",
"..#.........#...",
".......#........",
".......#........",
".....#.#.#......",
"......###.......",
".......#........",
"................"};

/* XPM */
static const char *New[]={
"22 22 53 1",
"# c None",
". c None",
"e c #000000",
"W c #2b2b2b",
"d c #323232",
"n c #343434",
"i c #363636",
"c c #3b3b3b",
"b c #3e3e3e",
"f c #3f3f3f",
"a c #454545",
"s c #969696",
"Y c #979797",
"m c #989898",
"r c #a1a1a1",
"V c #a3a3a3",
"T c #a7a7a7",
"A c #a8a8a8",
"R c #ababab",
"P c #b0b0b0",
"O c #b3b3b3",
"L c #b8b8b8",
"J c #bbbbbb",
"X c #bdbdbd",
"G c #c1c1c1",
"D c #c4c4c4",
"S c #c5c5c5",
"z c #c6c6c6",
"U c #c7c7c7",
"v c #c9c9c9",
"Q c #cacaca",
"q c #cdcdcd",
"l c #cfcfcf",
"h c #d2d2d2",
"N c #d4d4d4",
"M c #d8d8d8",
"y c #d9d9d9",
"K c #dddddd",
"I c #dedede",
"H c #e1e1e1",
"F c #e4e4e4",
"E c #e6e6e6",
"C c #e8e8e8",
"B c #eaeaea",
"x c #ededed",
"w c #eeeeee",
"u c #f2f2f2",
"t c #f3f3f3",
"p c #f5f5f5",
"o c #f6f6f6",
"k c #f8f8f8",
"j c #f9f9f9",
"g c #fcfcfc",
"......................",
"....#############.....",
"....#abcccccdef###....",
"....#bggggggheei###...",
"....#cjkkkkklemen###..",
"....#copppppqersen###.",
"....#ctuuuuuveeeee###.",
"....#cwxxxxxyzzzAe###.",
"....#cBCCCCCCCCCDe###.",
"....#cEFFFFFFFFFGe###.",
"....#cHIIIIIIIIIJe###.",
"....#cKyyyyyyyyyLe###.",
"....#cMNNNNNNNNNOe###.",
"....#cNlllllllllPe###.",
"....#clQQQQQQQQQRe###.",
"....#cQSSSSSSSSSTe###.",
"....#cUGGGGGGGGGVe###.",
"....#WXrrrrrrrrrYe###.",
"....#eeeeeeeeeeeee###.",
"....#################.",
"....#################.",
"....#################."};

/* XPM */
static const char *Open[]={
"22 22 236 2",
".# c None",
"Qt c None",
".a c #000000",
"bP c #060806",
"#9 c #080a08",
"bK c #0a0c0a",
"bt c #0f100f",
"a6 c #121510",
"bD c #121612",
"bi c #161a16",
".y c #191d19",
"aQ c #1c201c",
"bJ c #1c211a",
"#. c #272b27",
".S c #281515",
".d c #282a28",
"#a c #2c1919",
"#t c #2c1a1a",
"#4 c #2d1e1d",
"bC c #2f392d",
"#3 c #322826",
"#s c #372d2c",
"ay c #373e36",
"bE c #384137",
"#2 c #3a4239",
"bL c #3a4339",
"aj c #3b2d2d",
".g c #3e473c",
"ai c #413a38",
".R c #413c3c",
"#h c #424a41",
"#r c #424b42",
"an c #424c41",
"bs c #425241",
"#L c #443e3a",
"ag c #444e43",
"bj c #444f43",
"#T c #444f44",
"bI c #455143",
".9 c #465146",
"bq c #475446",
"#J c #495349",
"bu c #4a5549",
"ax c #4a554a",
"## c #4c4141",
".O c #4c554b",
"ah c #4f554b",
".o c #4f5a4e",
"aR c #4f5b4f",
".I c #515251",
"#1 c #525f51",
"#b c #544141",
".v c #545454",
"#A c #545b54",
".T c #554242",
"#K c #555a52",
"a7 c #556354",
"bh c #556a54",
"#q c #576456",
"#M c #584646",
"#u c #5a4747",
"bf c #5a6456",
".0 c #5b625b",
".z c #5b6759",
"#B c #5b6d5a",
".k c #5c5c5c",
"#5 c #604e4e",
"a2 c #60705f",
"aM c #616a60",
".Z c #626462",
"az c #635e5a",
"bM c #637061",
"a3 c #676361",
".H c #676867",
"#l c #677666",
"a5 c #678066",
".l c #6c6c6c",
".B c #707b6f",
"bO c #71806f",
".c c #737373",
"#g c #737973",
".1 c #737d73",
"#7 c #738372",
".C c #756c6c",
".m c #757775",
"bB c #758074",
"bF c #768675",
".u c #777777",
"al c #778176",
"bv c #778876",
"#R c #778c75",
"aP c #789576",
".D c #7c6f6f",
".Q c #7c8c7b",
"aA c #7d847d",
".U c #807272",
"#c c #817474",
"aw c #839381",
"be c #839581",
"#v c #857979",
"aO c #858884",
"bA c #869684",
".J c #878f87",
"#N c #887c7c",
"bN c #889786",
"a8 c #889986",
"aB c #88a886",
"bH c #899a88",
"bg c #8a8a8a",
"bk c #8a9b89",
"#0 c #8b9e8a",
"br c #8c8d8c",
"a4 c #8d8d8d",
".8 c #8d9f8c",
"aC c #8da08c",
"bG c #8e9f8c",
"a. c #8ea18c",
"#D c #8ea18d",
"#i c #8fa28e",
"bz c #90a18f",
"#6 c #918787",
"aL c #91a18f",
"#p c #91a28f",
".x c #939e93",
"aN c #948e8d",
"bp c #94a491",
"by c #94a593",
"#I c #95a693",
"af c #95a894",
".n c #969f95",
"bo c #97a995",
"bx c #97a996",
"am c #99bd97",
".w c #9a9d9a",
"bd c #9aab98",
"bn c #9aac98",
"bw c #9bad99",
".5 c #9bc099",
".p c #9c9999",
"a1 c #9daf9b",
"bc c #9eb09c",
"aS c #9eb19c",
".E c #a09797",
"ak c #a09898",
".e c #a1a4a1",
".A c #a1aba1",
"a0 c #a1b29f",
"bb c #a1b4a0",
"bm c #a1b4a1",
".V c #a39c9c",
".b c #a3a3a3",
"aK c #a3b6a2",
"#d c #a49e9e",
"aZ c #a4b7a2",
"ba c #a4b8a3",
"bl c #a5b8a3",
"#f c #a6a7a6",
"aJ c #a7baa5",
"#w c #a8a2a2",
".t c #a8a8a8",
"aY c #a8baa6",
"b# c #a8bba6",
"#8 c #a9d1a6",
"#O c #aaa3a3",
"aI c #aabea9",
"aX c #aabfaa",
"b. c #abbfaa",
"av c #adc1ab",
"aH c #adc1ac",
"aW c #aec2ac",
"a9 c #afc2ad",
"#j c #afc5ad",
"au c #b0c4ae",
".h c #b1b0b0",
"aG c #b1c5af",
"aV c #b1c6b0",
".P c #b2c7b0",
".N c #b3bbb2",
"at c #b3c7b2",
"aF c #b4c8b2",
"aU c #b4c9b2",
"ae c #b6cbb4",
"as c #b7ccb5",
".G c #b8b9b8",
"aT c #b8cdb6",
"#S c #b8e4b5",
".q c #b9b6b6",
".Y c #b9bab9",
"ad c #b9ceb8",
".F c #bab7b7",
"ar c #bacfb9",
".6 c #bad0b9",
".W c #bcbaba",
"ac c #bdd3bb",
"aq c #bdd4bc",
"#x c #bebcbc",
"#z c #bebebe",
".K c #bec7bd",
"aE c #bed4bc",
"#P c #c0bdbd",
"#Z c #c0d5be",
".2 c #c1d1c1",
"ab c #c1d7bf",
"ap c #c1d7c0",
"aD c #c1d8c1",
".3 c #c3d1c2",
"#Y c #c3d9c2",
"aa c #c4dac2",
"#C c #c4f3c1",
".j c #c5c5c5",
".4 c #c6cfc5",
".r c #c7c6c6",
"#e c #c7c7c7",
"#X c #c7ddc5",
"a# c #c7dec6",
"ao c #c7dfc6",
".X c #c8c7c7",
"#y c #c9c8c8",
"#Q c #c9c9c9",
".M c #c9d0c8",
"#H c #c9e0c7",
"#W c #cae1c8",
"#o c #cae2c9",
".i c #cbcbcb",
".s c #cccccc",
"#U c #cce3ca",
"#G c #cce4cb",
"#V c #cde4cb",
"#k c #cdfeca",
"#F c #cfe7ce",
".L c #d2d7d2",
"#E c #d2ead0",
".f c #d4d4d4",
".7 c #d4ebd2",
"#m c #d4ecd2",
"#n c #d4edd3",
"QtQtQtQt.#.#.#.#.#.#.#.#.#.#.#.#.#.#QtQtQtQt",
"QtQtQt.#.a.a.#.a.a.a.#.#.#.#.#.#.#.#.#.#.#.#",
".#.#.#.a.b.c.d.e.f.g.a.a.#.#.#.#.#.#.#.#.#.#",
".#.#.#.a.h.i.j.k.l.m.n.o.a.a.#.a.a.#.#.#.#.#",
".#.#.#.a.p.q.r.s.t.u.v.w.x.y.z.A.B.a.a.#.#.#",
".a.a.a.a.C.D.E.F.r.i.G.H.I.J.K.L.M.N.O.a.a.#",
".a.P.Q.y.R.S.T.U.V.W.X.s.Y.Z.0.1.2.3.4.5.a.#",
".a.6.7.8.9#.###a#b#c#d.W#e.i#f#g#h#i#j#k.a.#",
".##l#m#n#o#p#q#r#s#t#u#v#w#x#y.s#z#A#B#C.a.#",
".#.a#D#E#F#G#H#I#J#K#L#a#M#N#O#P#Q.s#R#S.a.#",
".#.##T#U#V#W#X#Y#Z#0#1#2#3#4#5#6.W.i#7#8.a.#",
".#.##9a.#oa#aaabacadaeafagahaiajak.ralam.a.#",
".#.#.#anaoaaapaqarasatauavawaxayaz.FaAaB.a.#",
".#.#.#.aaCaDaE.6asaFaGaHaIaJaKaLaMaNaOaP.a.#",
".#.#.#.#aQaRaSaTaUaVaWaXaYaZa0a1a2a3a4a5.a.#",
".#.#.#.#.#.#a6a7a8a9b.b#babbbcbdbebfbgbh.a.#",
".#.#.#.#.#.#.#.abibjbkblbmaSbnbobpbqbrbs.a.#",
"Qt.#.#.#.#.#.#.#.#.#btbubvbwbxbybzbAbBbC.a.#",
"QtQt.#.#.#.#.#.#.#.#.#.abDbEbF#pbGbHbIbJ.a.#",
"QtQtQt.#.#.#.#.#.#.#.#.#.#.abKbLbMbNbObP.a.#",
"QtQtQtQtQt.#.#.#.#.#.#.#.#.#.#.a.a.a.a.a.a.#",
"QtQtQtQtQtQtQt.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#"};

/* XPM */
static const char *Param_Bool[]={
"17 16 2 1",
"# c #000000",
". c #ffffff",
".................",
".................",
".................",
"....#######......",
"....##....##.....",
"....##....##.....",
"....##....##.....",
"....#######......",
"....##....##.....",
"....##....##.....",
"....##....##.....",
"....##....##.....",
"....#######......",
".................",
".................",
"................."};

/* XPM */
static const char *Param_Float[]={
"17 16 2 1",
"# c #000000",
". c #ffffff",
".................",
".................",
".................",
".....#######.....",
".....##..........",
".....##..........",
".....##..........",
".....######......",
".....##..........",
".....##..........",
".....##..........",
".....##..........",
".....##..........",
".................",
".................",
"................."};

/* XPM */
static const char *Param_Int[]={
"17 16 2 1",
"# c #000000",
". c #ffffff",
".................",
".................",
".................",
".......##........",
".......##........",
".......##........",
".......##........",
".......##........",
".......##........",
".......##........",
".......##........",
".......##........",
".......##........",
".................",
".................",
"................."};

/* XPM */
static const char *Param_Text[]={
"17 16 2 1",
"# c #000000",
". c #ffffff",
".................",
".................",
".................",
"....########.....",
".......##........",
".......##........",
".......##........",
".......##........",
".......##........",
".......##........",
".......##........",
".......##........",
".......##........",
".................",
".................",
"................."};

/* XPM */
static const char *Param_XML[]={
"17 16 2 1",
"# c #000000",
". c #ffffff",
".................",
".................",
".................",
"....##.....##....",
"....##.....##....",
".....##...##.....",
"......##.##......",
".......###.......",
".......###.......",
"......##.##......",
".....##...##.....",
"....##.....##....",
"....##.....##....",
".................",
".................",
"................."};

/* XPM */
static const char *Part_Box[]={
"16 16 3 1",
". c None",
"# c #000000",
"a c #c6c642",
"................",
".......#######..",
"......#aaaaa##..",
".....#aaaaa###..",
"....#aaaaa##a#..",
"...#aaaaa##aa#..",
"..#aaaaa##aaa#..",
".########aaaa#..",
".#aaaaa#aaaaa#..",
".#aaaaa#aaaa##..",
".#aaaaa#aaa##...",
".#aaaaa#aa##....",
".#aaaaa#a##.....",
".#aaaaa###......",
".########.......",
"................"};

/* XPM */
static const char *Paste[]={
"22 22 140 2",
".# c None",
"Qt c None",
".a c #000000",
".Z c #0a0a0a",
"ai c #202020",
".Y c #262626",
".X c #2d2d2d",
".9 c #303030",
"af c #332810",
"ag c #342a10",
".q c #342c19",
".W c #343434",
"ah c #362a12",
".Q c #372a12",
".w c #373737",
".k c #382f1d",
"ac c #3b2f13",
"ae c #3c3013",
".E c #413315",
"ad c #433616",
".h c #434343",
".s c #493918",
".i c #493e26",
".C c #4a3a18",
".b c #4b4b4b",
".B c #4e3e19",
".p c #505050",
".y c #5b471d",
"#9 c #8a723c",
".r c #8b723c",
".g c #8b8b8b",
".j c #8e784b",
".c c #929292",
"#q c #939393",
".L c #967631",
"#g c #969696",
"a. c #977731",
".M c #977732",
".N c #987831",
".K c #987832",
"#1 c #9a7932",
".O c #9b7a31",
"aa c #9b7a32",
"#5 c #9b7b33",
".t c #9b8351",
".J c #9c7a32",
"#U c #9c7b32",
"a# c #9c7b33",
"#L c #9d7b33",
"#2 c #9d7c32",
"#P c #9d7c33",
"#C c #9e7c33",
"#p c #9e9e9e",
"#V c #9f7c33",
"#M c #9f7d33",
"#s c #9f7e33",
"#W c #a07e33",
"#x c #a07e34",
"#D c #a17e33",
".I c #a17e34",
"#i c #a17f33",
"#t c #a17f34",
"## c #a18034",
".P c #a27f34",
".V c #a28034",
"#3 c #a28134",
"#N c #a28136",
".H c #a38034",
".R c #a38134",
".G c #a38136",
".S c #a48136",
".1 c #a48234",
".U c #a48236",
".T c #a58134",
"#j c #a58136",
"#O c #a58236",
"#4 c #a58336",
".A c #a58338",
"#u c #a68236",
".2 c #a68336",
".x c #a68536",
".6 c #a78336",
"#v c #a78436",
"#a c #a78537",
".o c #a7a7a7",
".D c #a88436",
".3 c #a88536",
"#k c #a88537",
"#0 c #a88d53",
".n c #a8a8a8",
"#E c #a98536",
"#b c #a98537",
"#w c #a98637",
".v c #a9a9a9",
".4 c #aa8637",
"#l c #aa8737",
"#T c #aa8f54",
"#K c #aa8f55",
".m c #aaaaaa",
".5 c #ab8737",
"#c c #ab8738",
".u c #ab8c4a",
"#B c #ab9056",
"#J c #ababab",
"#r c #ac9155",
"#h c #ad9156",
"#. c #ae9256",
"aj c #aeaeae",
".0 c #af9256",
".F c #af9357",
".z c #b19559",
".l c #b1b1b1",
"ab c #b3b3b3",
".f c #b4b4b4",
".e c #b5b5b5",
".d c #b6b6b6",
"#8 c #bababa",
"#I c #bdbdbd",
"#Z c #c0c0c0",
"#A c #c2c2c2",
"#S c #c7c7c7",
"#o c #c8c8c8",
"#f c #cdcdcd",
"#7 c #cecece",
"#H c #d0d0d0",
".8 c #d2d2d2",
"#6 c #d3d3d3",
"#Y c #d4d4d4",
"#X c #d9d9d9",
"#R c #dcdcdc",
"#Q c #dfdfdf",
"#G c #e3e3e3",
"#F c #e6e6e6",
"#z c #e9e9e9",
"#y c #ececec",
"#n c #f0f0f0",
"#m c #f2f2f2",
"#e c #f6f6f6",
"#d c #f7f7f7",
".7 c #fcfcfc",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQt.#.a.a.a.a.a.#.#.#QtQtQtQtQtQtQtQt",
"QtQt.#.a.a.b.c.d.e.f.g.h.a.a.#.#.#QtQtQtQtQt",
"Qt.#.i.j.k.c.l.m.n.n.o.p.q.r.s.#.#.#QtQtQtQt",
"Qt.a.t.u.a.v.b.w.w.w.w.w.a.x.y.a.#.#QtQtQtQt",
"Qt.a.z.A.B.a.a.a.a.a.a.a.C.D.E.a.#.#QtQtQtQt",
"Qt.a.F.G.H.I.J.K.L.M.L.N.O.P.Q.a.#.#.#.#QtQt",
"Qt.a.F.R.S.T.G.R.U.V.W.X.X.X.Y.a.Z.#.#.#.#Qt",
"Qt.a.0.V.1.2.3.4.5.6.X.7.7.7.8.a.a.9.#.#.#.#",
"Qt.a#.##.G.2#a#b#c.V.X#d#e#e#f.a#g.a.9.#.#.#",
"Qt.a#h#i.V#j.2#k#l.I.X#m#n#n#o.a#p#q.a.9.#.#",
"Qt.a#r#s#t.R#u#v#w#x.X#y#z#z#A.a.a.a.a.a.#.#",
"Qt.a#B#C#D.V.1.2#E#C.X#F#G#G#H#I#I#I#J.a.#.#",
"Qt.a#K#L#M#t#N#O#v#P.X#Q#R#R#R#R#R#R#S.a.#.#",
"Qt.a#T#U#V#W.V.S.2#P.X#X#Y#Y#Y#Y#Y#Y#Z.a.#.#",
"Qt.a#0#1#2#s#t#3#4#5.X#6#7#7#7#7#7#7#8.a.#.#",
"Qt.a#9a.a##M#x.V.1aa.X#f#S#S#S#S#S#Sab.a.#.#",
"Qt.#acadaeafagagahafai#Zajajajajajaj.n.a.#.#",
"Qt.#.#.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.a.#.#",
"Qt.#.#.#.#.#.#.#.#.#.#.#.a.a.a.a.a.a.#.#.#.#",
"QtQt.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#",
"QtQtQtQtQtQtQtQtQt.#.#.#.#.#.#.#.#.#.#.#.#.#"};

/* XPM */
static const char *Play[]={
"16 16 2 1",
"# c #008200",
". c #d6d3ce",
"................",
".##.............",
".####...........",
".#####..........",
".#######........",
".#########......",
".##########.....",
".############...",
".############...",
".##########.....",
".########.......",
".#######........",
".#####..........",
".###............",
".##.............",
"................"};

/* XPM */
static const char *PrefTree_GroupClosed[]={
"16 16 10 1",
". c None",
"# c #000000",
"e c #323232",
"f c #565656",
"b c #868686",
"d c #a0a0a4",
"g c #c2c2c2",
"h c #dadada",
"a c #ffb848",
"c c #ffe2b1",
"....###.........",
"....#ab##.......",
"....#acab####...",
"###.#acccccca#..",
"#ddefaaaccccca#.",
"#bdddbaaaacccab#",
".eddddbbaaaacab#",
".#bddggdbbaaaab#",
"..edgdggggbbaab#",
"..#bgggghghdaab#",
"...ebhgggh.cfab#",
"....#edhh...dab#",
"......#eg...cfb#",
"........#eg..bb#",
"..........#eg.b#",
"............#ee#"};

/* XPM */
static const char *PrefTree_GroupOpen[]={
"16 16 8 1",
". c None",
"# c #000000",
"a c #565656",
"f c #868686",
"e c #a0a0a4",
"b c #b9b900",
"d c #c2c2c2",
"c c #ffff00",
"..###...........",
".#abc##.........",
".#.aabc#####....",
".#..daabbccc#...",
".#.d.ddabbbba...",
".#d.ddddaaaab#..",
".#.ddddddded#ba.",
".#dddddddede#ba.",
".#ddddddedee#ba.",
".#dddddedeee#ba.",
".##fddedeeee#ba.",
"...##fdeeeee#ba.",
".....##eeeee#ba.",
".......##eee#b##",
".........##e#b##",
"...........####."};

/* XPM */
static const char *PrefTree_PrefPage[]={
"16 16 5 1",
". c None",
"# c #000000",
"c c #503200",
"b c #b9b900",
"a c #ffffd4",
".........#......",
"......#.#a##....",
".....#.#...a##..",
"....#.#...a...#.",
"...#.#..a##..#..",
"..#.#a..#..##...",
".#a#aa.#...a.##.",
"#a#aaa#.b......#",
"#bbcb#.b..b...#.",
".##b#.b..ba..#..",
"...#ab.ab...#...",
"..#aaaaba.a#....",
"...##aaaaa#.....",
".....##aa#......",
".......##.......",
"................"};

/* XPM */
static const char *Print[]={
"22 22 77 2",
".# c None",
".O c None",
".B c None",
"Qt c None",
".e c #000000",
".9 c #00d400",
".G c #161616",
".T c #222222",
".n c #2a2a2a",
".i c #2c2c2c",
".d c #323232",
".J c #393939",
".f c #3a3a3a",
".c c #3b3b3b",
".b c #3e3e3e",
".a c #454545",
"#k c #4e4e3e",
".N c #555544",
".S c #585858",
".R c #676767",
".Q c #737373",
"#j c #7a7a61",
".C c #7b7b7b",
"#g c #7c7c63",
"#f c #808066",
"#i c #828267",
".P c #828282",
"#h c #848469",
".H c #858585",
"#b c #8f8f71",
"#. c #959575",
".s c #969696",
".m c #989898",
".6 c #9b9b7a",
".Y c #9e9e7d",
".r c #a1a1a1",
".2 c #a3a381",
"#e c #a6a683",
".A c #a8a8a8",
"#d c #abab88",
"#a c #b3b38d",
".I c #b4b4a1",
".M c #b9b9b9",
"#c c #baba9e",
".8 c #bbbb94",
".4 c #c3c39a",
"## c #c3c3a5",
".F c #c4c4c4",
".z c #c6c6c6",
".U c #c7c7b3",
".7 c #c9c9aa",
".v c #c9c9c9",
".1 c #cacaa0",
".0 c #cccca3",
".q c #cdcdcd",
".3 c #cfcfaf",
".l c #cfcfcf",
".h c #d2d2d2",
".5 c #d40000",
".Z c #d8d8b9",
".X c #d9d9b5",
".W c #d9d9b7",
".y c #d9d9d9",
".L c #dadada",
".V c #dcdcbc",
".K c #dddddd",
".E c #e8e8e8",
".D c #eaeaea",
".x c #ededed",
".w c #eeeeee",
".u c #f2f2f2",
".t c #f3f3f3",
".p c #f5f5f5",
".o c #f6f6f6",
".k c #f8f8f8",
".j c #f9f9f9",
".g c #fcfcfc",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt",
"QtQtQt.#.#.#.#.#.#.#.#.#.#.#.#.#.#QtQtQtQtQt",
"QtQtQt.#.a.b.c.c.c.c.c.d.e.f.#.#.#.#QtQtQtQt",
"QtQtQt.#.b.g.g.g.g.g.g.h.e.e.i.#.#.#.#QtQtQt",
"QtQtQt.#.c.j.k.k.k.k.k.l.e.m.e.n.#.#.#.#QtQt",
"QtQtQt.#.c.o.p.p.p.p.p.q.e.r.s.e.n.#.#.#QtQt",
"QtQtQt.#.c.t.u.u.u.u.u.v.e.e.e.e.e.#.#.#QtQt",
"QtQt.#.#.c.w.x.x.x.x.x.y.z.z.z.A.e.#.#.#.#Qt",
"Qt.#.B.C.c.D.E.E.E.E.E.E.E.E.E.F.e.G.e.#.#.#",
"Qt.#.H.I.J.K.L.L.L.L.L.L.L.L.L.M.e.N.e.#.#.#",
".#.O.P.Q.R.R.R.R.R.R.R.R.R.R.R.R.R.S.T.e.#.#",
".#.H.U.V.W.W.W.W.W.W.W.W.W.W.W.W.W.X.Y.e.#.#",
".#.Q.Z.0.1.1.1.1.1.1.1.1.1.1.1.1.1.1.2.e.#.#",
".#.R.3.4.5.5.4.4.4.4.4.4.4.4.4.4.4.4.6.e.#.#",
".#.R.7.8.9.9.8.8.8.8.8.8.8.8.8.8.8.8#..e.#.#",
".#.R###a#a#a#a#a#a#a#a#a#a#a#a#a#a#a#b.e.#.#",
".#.S#c#d#d#d#d#d#d#d#d#d#d#d#d#d#d#e#f.e.#.#",
".#.n#g#h#i#i#i#i#i#i#i#i#i#i#i#i#i#j#k.e.#.#",
".#.#.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.#.#",
".#.#.#.#.#.e.e.e.e.e.e.e.e.e.e.e.e.e.#.#.#.#",
".#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#",
"Qt.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#"};

/* XPM */
static const char *RawTree_Attr[]={
"16 16 5 1",
". c None",
"# c #000000",
"c c #503200",
"b c #b9b900",
"a c #ffffd4",
".........#......",
"......#.#a##....",
".....#.#...a##..",
"....#.#...a...#.",
"...#.#..a##..#..",
"..#.#a..#..##...",
".#a#aa.#...a.##.",
"#a#aaa#.b......#",
"#bbcb#.b..b...#.",
".##b#.b..ba..#..",
"...#ab.ab...#...",
"..#aaaaba.a#....",
"...##aaaaa#.....",
".....##aa#......",
".......##.......",
"................"};

/* XPM */
static const char *RawTree_LabelClosed[]={
"16 16 10 1",
". c None",
"# c #000000",
"e c #323232",
"f c #565656",
"b c #868686",
"d c #a0a0a4",
"g c #c2c2c2",
"h c #dadada",
"a c #ffb848",
"c c #ffe2b1",
"....###.........",
"....#ab##.......",
"....#acab####...",
"###.#acccccca#..",
"#ddefaaaccccca#.",
"#bdddbaaaacccab#",
".eddddbbaaaacab#",
".#bddggdbbaaaab#",
"..edgdggggbbaab#",
"..#bgggghghdaab#",
"...ebhgggh.cfab#",
"....#edhh...dab#",
"......#eg...cfb#",
"........#eg..bb#",
"..........#eg.b#",
"............#ee#"};

/* XPM */
static const char *RawTree_LabelOpen[]={
"16 16 8 1",
". c None",
"# c #000000",
"a c #565656",
"f c #868686",
"e c #a0a0a4",
"b c #b9b900",
"d c #c2c2c2",
"c c #ffff00",
"..###...........",
".#abc##.........",
".#.aabc#####....",
".#..daabbccc#...",
".#.d.ddabbbba...",
".#d.ddddaaaab#..",
".#.ddddddded#ba.",
".#dddddddede#ba.",
".#ddddddedee#ba.",
".#dddddedeee#ba.",
".##fddedeeee#ba.",
"...##fdeeeee#ba.",
".....##eeeee#ba.",
".......##eee#b##",
".........##e#b##",
"...........####."};

/* XPM */
static const char *Record[]={
"16 16 3 1",
"# c #000000",
"a c #840000",
". c #d6d3ce",
"......###.......",
"....#aaaaaa#....",
"..##aaaaaaaa#...",
"..#aaaaaaaaaa#..",
".#aaaaaaaaaaaa#.",
".aaaaaaaaaaaaa#.",
"#aaaaaaaaaaaaa#.",
"#aaaaaaaaaaaaaa.",
"#aaaaaaaaaaaaaa.",
".aaaaaaaaaaaaa#.",
".#aaaaaaaaaaaa#.",
".#aaaaaaaaaaa#..",
"..#aaaaaaaaaa#..",
"...#aaaaaaa#....",
".....##aa##.....",
"................"};

/* XPM */
static const char *pRedo[]={
"24 24 21 1",
"j c None",
"l c None",
"n c None",
"h c None",
"i c None",
"s c None",
"k c None",
"m c None",
"r c None",
"q c None",
"p c None",
"o c None",
". c None",
"# c None",
"b c #000000",
"a c #299663",
"d c #29cb94",
"c c #29ff94",
"e c #cecfe7",
"f c #ceff94",
"g c #ffffff",
"........................",
"........................",
"........................",
"..##################....",
"..##################....",
"..#...aaaaa.............",
"..#..bcccccaa...........",
"..#.bdcddddccaa.....a...",
"..#bdcdbbbbddcca...ba...",
"..#bdca....bbdccaebfa...",
"..#bdca......bdccbfga...",
"..#bdca.......bdcfgfa...",
"..#bdca.......ebdcfga...",
"..#bdca.......bdcccfa...",
"..#.bdca.....bddddddah..",
"..#.bdca....bbbbbbbbb.i.",
"..#..bdca...j.i.h.h.ii.k",
".....bdca..h.h.h.h.l..m.",
"......bbb.h.n.......hk..",
"oooooohonooooojonononooo",
"pppppjpipppppkpkpkpkpppp",
"qqqqnqnqqqqqqqqqqqqqqqqq",
"rrrrrkrrrrrrrrrrrrrrrrrr",
"ssssssssssssssssssssssss"};

/* XPM */
static const char *Redo[]={
"22 22 94 2",
".# c None",
"#y c None",
"#B c None",
".a c None",
".g c None",
"Qt c None",
".f c #000000",
"#o c #002d00",
"#i c #002e00",
".9 c #002f00",
".Y c #003d00",
"#w c #005000",
"#l c #005600",
".P c #005d00",
"#h c #006000",
".H c #006100",
"#n c #006200",
".x c #006300",
".n c #006400",
"#r c #006e00",
".X c #007900",
"#t c #007b00",
"#d c #008900",
"#e c #008a00",
"#c c #008b00",
"#g c #008e00",
".8 c #009000",
"#f c #009300",
"#a c #009500",
"#k c #009600",
"#b c #009900",
".W c #009d00",
"#v c #009f00",
"#m c #00a400",
"## c #00a500",
".7 c #00a600",
".3 c #00aa00",
".V c #00ac00",
".4 c #00ad00",
".1 c #00b100",
".2 c #00b200",
".5 c #00ba00",
".6 c #00bc00",
".O c #00bd00",
".U c #00c100",
".N c #00c500",
".T c #00c800",
".G c #00cb00",
".M c #00cc00",
".w c #00ce00",
"#z c #050505",
".0 c #06c406",
".S c #08c908",
".L c #08cd08",
"#s c #121212",
".c c #131313",
"#A c #161616",
"#q c #1ebc1e",
".F c #1ed31e",
".e c #227722",
".K c #24d124",
"#x c #272727",
"#j c #29c229",
"#u c #303030",
".E c #30d630",
".C c #31d731",
".D c #33d733",
"#. c #34c934",
".R c #37d137",
".B c #37d737",
".v c #38da38",
".m c #3bdd3b",
".Z c #45d045",
".J c #49d749",
".A c #49da49",
"#p c #4c4c4c",
".b c #4d4d4d",
".k c #515151",
".s c #51de51",
".j c #565656",
".t c #56df56",
".Q c #57d757",
".r c #57df57",
".d c #5b5b5b",
".u c #5be05b",
".i c #5f5f5f",
".I c #61ce61",
".q c #61d261",
".z c #61de61",
".h c #666666",
".y c #6ab36a",
".p c #6ab56a",
".l c #6da16d",
".o c #6e6e6e",
"QtQtQtQtQtQtQtQtQtQtQtQt.#.#.#QtQtQtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQt.#.a.#.#.#.#QtQtQtQtQt",
"QtQtQtQtQtQtQtQtQtQtQt.#.b.c.#.#.#.#QtQtQtQt",
"QtQtQt.#.#.#.#.#.#.#.#.#.d.e.f.#.#.#.#QtQtQt",
"QtQt.#.g.h.i.j.k.k.k.k.i.l.m.n.f.#.#.#.#QtQt",
"Qt.#.g.o.p.q.r.s.s.s.s.t.u.v.w.x.f.#.#.#.#Qt",
"Qt.#.h.y.z.A.B.C.C.C.C.D.E.F.w.G.H.f.#.#.#.#",
"Qt.#.i.I.J.K.L.M.M.M.M.M.M.M.M.N.O.P.f.#.#.#",
"Qt.#.j.Q.R.S.T.T.T.T.T.T.T.T.U.V.W.X.Y.#.#.#",
"Qt.#.k.Z.0.1.2.V.3.3.3.4.5.6.7.8.x.9.f.#.#.#",
"Qt.#.k#.###a#b#c#d#e#e#f.3###g#h#i.f.#.#.#.#",
"Qt.#.k#j#k.f.P.Y.f.f.f.f#l#m#n#o.f.#.#.#.#.#",
"Qt.##p#q#r.f.f.f.#.#.#.##s#t#i.f.#.#.#.#.#Qt",
"Qt.##u#v#w.f.#.#.#.#.#.##s.f.f.#.#.#.#.#QtQt",
"Qt.##x.f#i.f.#.#.#.#.#.#.f.#.#.#.#.#.#QtQtQt",
"Qt.##y#s.f.f.#.#.#.#Qt.#.#.#.#.#.#.#QtQtQtQt",
"Qt.#.##z.f.f.f.#.#.#.#.#.#.#.#.#.#QtQtQtQtQt",
"Qt.#.#.#.f.f.f#A#B.#.#.#.#.#.#.#.#.#.#QtQtQt",
"QtQt.#.#.#.#.f.f.f.f.f.f.f.f.f.f.#.#.#QtQtQt",
"QtQtQt.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#QtQt",
"QtQtQtQt.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#QtQtQt",
"QtQtQtQtQt.#.#.#.#.#.#.#.#.#.#.#.#.#.#QtQtQt"};

/* XPM *//*
static const char *Redo[]={
"24 24 8 1",
". c None",
"a c #000000",
"# c #299663",
"c c #29cb94",
"b c #29ff94",
"d c #cecfe7",
"e c #ceff94",
"f c #ffffff",
"........................",
"........................",
"........................",
"........................",
"........................",
"......#####.............",
".....abbbbb##...........",
"....acbccccbb##.....#...",
"...acbcaaaaccbb#...a#...",
"...acb#....aacbb#dae#...",
"...acb#......acbbaef#...",
"...acb#.......acbefe#...",
"...acb#.......dacbef#...",
"...acb#.......acbbbe#...",
"....acb#.....acccccc#...",
"....acb#....aaaaaaaaa...",
".....acb#...............",
".....acb#...............",
"......aaa...............",
"........................",
"........................",
"........................",
"........................",
"........................"};
*/
/* XPM */
static const char *Save[]={
"22 22 44 1",
"# c None",
"a c None",
". c None",
"c c #000000",
"d c #080808",
"b c #151515",
"O c #1c2600",
"N c #1d1d1d",
"A c #1d2a00",
"u c #1e2a00",
"w c #202d00",
"t c #2c3713",
"v c #303a1a",
"J c #343434",
"r c #394f00",
"l c #3a5004",
"p c #3b3b3b",
"k c #424242",
"P c #425b00",
"e c #4c4c4c",
"j c #5e8300",
"M c #628800",
"s c #668e00",
"o c #689000",
"x c #6c6c6c",
"E c #727272",
"B c #737373",
"L c #75a400",
"m c #787878",
"n c #78a800",
"f c #7e9b3e",
"y c #858585",
"i c #85af21",
"q c #86b023",
"g c #89b22a",
"C c #a0a0a0",
"z c #a6a6a6",
"F c #a8a8a8",
"H c #aaaaaa",
"D c #b2b2b2",
"G c #b7b7b7",
"I c #b8b8b8",
"K c #bababa",
"h c #ffffff",
"..####################",
".#abccccccccccccccd###",
".#efghhhhhhhhhhhhijc##",
".#kglhmmmmmmmhmmhnoc##",
".#pqrhhhhhhhhhhhhnsc##",
".#pqnhmmmmmmmhmmhnsc##",
".#pqnhhhhhhhhhhhhnsc##",
".#pqnhmmmhmmmhmmhnsc##",
".#pqnhhhhhhhhhhhhnsc##",
".#pqnhhhhhhhhhhhhnsc##",
".#pqnnnnnnnnnnnnnnsc##",
".#pqntccccccccccunsc##",
".#pqncvwwwwwxyzAcnsc##",
".#pqncwwwwwwBCDwcnsc##",
".#pqncwwwwwwEFGwcnsc##",
".#pqncwwwwwwyHIwcnsc##",
".#JincwwwwwwzDKwcLMc##",
".#NjocOOOOOOOOOOcMPc##",
".##ccccccccccccccccc##",
".#####################",
".#####################",
"..####################"};

/* XPM */
static const char *settings[]={
"16 16 7 1",
"# c #000080",
"e c #008080",
"d c #800000",
"a c #808080",
". c #d4d0c8",
"c c #ff0000",
"b c #ffffff",
"................",
"################",
"################",
"aaaaaaaaaaaaaaaa",
"abbbbbbbbbbbbbba",
"abbbbbbbbbbbbbba",
"abbbbbbbbaabbbba",
"abbbbbbbaaabbbba",
"abbbbbbaabbbbbba",
"abbbbccdbbbbbbba",
"abbbccccbbbbbbba",
"abbccccbbbbbbbba",
"abbcccbbbbbbbbba",
"aaaaaaaaaaaaaaaa",
"eeeeeeeeeeeeeeee",
"................"};

/* XPM */
static const char *Std_MacroPause[]={
"16 16 2 1",
". c None",
"# c #f90000",
"................",
"................",
"...####...####..",
"...####...####..",
"...####...####..",
"...####...####..",
"...####...####..",
"...####...####..",
"...####...####..",
"...####...####..",
"...####...####..",
"...####...####..",
"...####...####..",
"...####...####..",
"................",
"................"};

/* XPM */
static const char *Std_MacroPlay[]={
"16 16 2 1",
". c None",
"# c #64f538",
"................",
"................",
"..#.............",
"..###...........",
"..#####.........",
"..#######.......",
"..#########.....",
"..###########...",
"..##########....",
"..########......",
"..######........",
"..#####.........",
"..###...........",
"..#.............",
"................",
"................"};

/* XPM */
static const char *Std_MacroRecord[]={
"16 16 2 1",
". c None",
"# c #f90000",
"................",
".......##.......",
".....######.....",
"....########....",
"...##########...",
"..############..",
"..############..",
".##############.",
".##############.",
"..############..",
"..############..",
"...##########...",
"....########....",
".....######.....",
".......##.......",
"................"};

/* XPM */
static const char *Std_MacroStop[]={
"16 16 2 1",
". c None",
"# c #f90000",
"................",
"................",
"..############..",
"..############..",
"..############..",
"..############..",
"..############..",
"..############..",
"..############..",
"..############..",
"..############..",
"..############..",
"..############..",
"..############..",
"................",
"................"};

/* XPM */
static const char *Std_MDINormal[]={
"32 32 2 1",
". c None",
"# c #000000",
"................................",
"................................",
"..############################..",
"..############################..",
"..##........................##..",
"..##........................##..",
"..############################..",
"..############################..",
"..##..............##........##..",
"..##..............##........##..",
"..##..............##........##..",
"..##..............##........##..",
"..##..............##........##..",
"..##..............##........##..",
"..##..............##........##..",
"..##..............##........##..",
"..##..............##........##..",
"..##..............##........##..",
"..##..............##........##..",
"..##..............##........##..",
"..##..............##........##..",
"..##..............##........##..",
"..##..............##........##..",
"..##..............##........##..",
"..##..............##........##..",
"..##..............##........##..",
"..##..............##........##..",
"..##..............##........##..",
"..############################..",
"..############################..",
"................................",
"................................"};

/* XPM */
static const char *Std_MDIToplevel[]={
"32 32 2 1",
". c None",
"# c #000000",
"................................",
"................................",
"..############################..",
"..############################..",
"..##........................##..",
"..##........................##..",
"..############################..",
"..############################..",
"................................",
"................................",
"..##############..############..",
"..##############..############..",
"..##..........##..##........##..",
"..##..........##..##........##..",
"..##..........##..##........##..",
"..##..........##..##........##..",
"..##..........##..##........##..",
"..##..........##..##........##..",
"..##..........##..##........##..",
"..##..........##..##........##..",
"..##..........##..##........##..",
"..##..........##..##........##..",
"..##..........##..##........##..",
"..##..........##..##........##..",
"..##..........##..##........##..",
"..##..........##..##........##..",
"..##..........##..##........##..",
"..##..........##..##........##..",
"..##############..############..",
"..##############..############..",
"................................",
"................................"};

/* XPM */
static const char *Std_Tool1[]={
"16 16 4 1",
". c None",
"# c #000000",
"b c #800000",
"a c #808000",
"......####......",
".....##aa###....",
".......##aaa#...",
"........#aaa#...",
"........##aa##..",
".......#b###aa#.",
"......#b#..#a#..",
".....#b#....#...",
"....#b#.......#.",
"...#b#.......##.",
"..#b#.........#.",
".#b#..........#.",
"#b#...........#.",
"##...........###",
"................",
"................"};

/* XPM */
static const char *Std_Tool10[]={
"16 16 5 1",
". c None",
"# c #000000",
"b c #800000",
"a c #808000",
"c c #868686",
"................",
"......####......",
".....##aa###....",
".......##aaa#...",
"........#aaa#...",
"........##aa##..",
".......#b###aa#.",
"......#b#..#a#..",
".....#b#....#...",
"....#b#....#.c#c",
"...#b#....##.#.#",
"..#b#......#.#.#",
".#b#.......#.#.#",
"#b#........#.#.#",
"##........###c#c",
"................"};

/* XPM */
static const char *Std_Tool11[]={
"16 16 4 1",
". c None",
"# c #000000",
"b c #800000",
"a c #808000",
"................",
"......####......",
".....##aa###....",
".......##aaa#...",
"........#aaa#...",
"........##aa##..",
".......#b###aa#.",
"......#b#..#a#..",
".....#b#....#...",
"....#b#....#..#.",
"...#b#....##.##.",
"..#b#......#..#.",
".#b#.......#..#.",
"#b#........#..#.",
"##........######",
"................"};

/* XPM */
static const char *Std_Tool12[]={
"16 16 5 1",
". c None",
"# c #000000",
"b c #800000",
"a c #808000",
"c c #868686",
"................",
"......####......",
".....##aa###....",
".......##aaa#...",
"........#aaa#...",
"........##aa##..",
".......#b###aa#.",
"......#b#..#a#..",
".....#b#....#...",
"....#b#....#.c#c",
"...#b#....##.#.#",
"..#b#......#...#",
".#b#.......#..#.",
"#b#........#.#..",
"##........######",
"................"};

/* XPM */
static const char *Std_Tool2[]={
"16 16 5 1",
". c None",
"# c #000000",
"b c #800000",
"a c #808000",
"c c #868686",
"................",
"......####......",
".....##aa###....",
".......##aaa#...",
"........#aaa#...",
"........##aa##..",
".......#b###aa#.",
"......#b#..#a#..",
".....#b#....#...",
"....#b#......c#c",
"...#b#.......#.#",
"..#b#..........#",
".#b#..........#.",
"#b#..........#..",
"##...........###",
"................"};

/* XPM */
static const char *Std_Tool3[]={
"16 16 5 1",
". c None",
"# c #000000",
"b c #800000",
"a c #808000",
"c c #868686",
"................",
"......####......",
".....##aa###....",
".......##aaa#...",
"........#aaa#...",
"........##aa##..",
".......#b###aa#.",
"......#b#..#a#..",
".....#b#....#...",
"....#b#......##.",
"...#b#.........#",
"..#b#........##.",
".#b#...........#",
"#b#............#",
"##...........##c",
"................"};

/* XPM */
static const char *Std_Tool4[]={
"16 16 5 1",
". c None",
"# c #000000",
"b c #800000",
"a c #808000",
"c c #868686",
"................",
"......####......",
".....##aa###....",
".......##aaa#...",
"........#aaa#...",
"........##aa##..",
".......#b###aa#.",
"......#b#..#a#..",
".....#b#....#...",
"....#b#.......#.",
"...#b#.......c#.",
"..#b#........##.",
".#b#........#.#.",
"#b#.........####",
"##............#.",
"................"};

/* XPM */
static const char *Std_Tool5[]={
"16 16 5 1",
". c None",
"# c #000000",
"b c #800000",
"a c #808000",
"c c #868686",
"................",
"......####......",
".....##aa###....",
".......##aaa#...",
"........#aaa#...",
"........##aa##..",
".......#b###aa#.",
"......#b#..#a#..",
".....#b#....#...",
"....#b#......###",
"...#b#.......#..",
"..#b#........##c",
".#b#...........#",
"#b#............#",
"##...........##c",
"................"};

/* XPM */
static const char *Std_Tool6[]={
"16 16 5 1",
". c None",
"# c #000000",
"b c #800000",
"a c #808000",
"c c #868686",
"................",
"......####......",
".....##aa###....",
".......##aaa#...",
"........#aaa#...",
"........##aa##..",
".......#b###aa#.",
"......#b#..#a#..",
".....#b#....#...",
"....#b#.......#.",
"...#b#.......#..",
"..#b#........##.",
".#b#.........#.#",
"#b#..........#.#",
"##...........c#c",
"................"};

/* XPM */
static const char *Std_Tool7[]={
"16 16 4 1",
". c None",
"# c #000000",
"b c #800000",
"a c #808000",
"................",
"......####......",
".....##aa###....",
".......##aaa#...",
"........#aaa#...",
"........##aa##..",
".......#b###aa#.",
"......#b#..#a#..",
".....#b#....#...",
"....#b#......###",
"...#b#.........#",
"..#b#..........#",
".#b#..........#.",
"#b#...........#.",
"##............#.",
"................"};

/* XPM */
static const char *Std_Tool8[]={
"16 16 5 1",
". c None",
"# c #000000",
"b c #800000",
"a c #808000",
"c c #868686",
"................",
"......####......",
".....##aa###....",
".......##aaa#...",
"........#aaa#...",
"........##aa##..",
".......#b###aa#.",
"......#b#..#a#..",
".....#b#....#...",
"....#b#......c#c",
"...#b#.......#.#",
"..#b#........c#c",
".#b#.........#.#",
"#b#..........#.#",
"##...........c#c",
"................"};

/* XPM */
static const char *Std_Tool9[]={
"16 16 5 1",
". c None",
"# c #000000",
"b c #800000",
"a c #808000",
"c c #868686",
"................",
"......####......",
".....##aa###....",
".......##aaa#...",
"........#aaa#...",
"........##aa##..",
".......#b###aa#.",
"......#b#..#a#..",
".....#b#....#...",
"....#b#......c#c",
"...#b#.......#.#",
"..#b#........#.#",
".#b#..........##",
"#b#............#",
"##............#.",
"................"};

/* XPM */
static const char *Std_WindowCascade[]={
"16 16 3 1",
"# c None",
". c #000080",
"a c #ffffff",
"..........######",
".a........######",
"..........######",
".aaaaaaaa.######",
".a..........####",
".a.a........####",
"............####",
"##.aaaaaaaa.####",
"##.aa..........#",
"##.aa.a........#",
"##.............#",
"#####.aaaaaaaa.#",
"#####.aaaaaaaa.#",
"#####.aaaaaaaa.#",
"#####..........#",
"################"};

/* XPM */
static const char *Std_WindowNew[]={
"16 16 4 1",
". c None",
"b c #000080",
"# c #008080",
"a c #ffffff",
".....##########.",
".....#a########.",
".....##########.",
".....#aaaaaaaa#.",
"##########aaaa#.",
"#a########aaaa#.",
"###############.",
"#aaaaaaaa#......",
"#aaaaabbbbbbbbbb",
"#aaaaababbbbbbbb",
"######bbbbbbbbbb",
"......baaaaaaaab",
"......baaaaaaaab",
"......baaaaaaaab",
"......bbbbbbbbbb",
"................"};

/* XPM */
static const char *Std_WindowNext[]={
"16 16 6 1",
"# c None",
"a c #000000",
". c #000080",
"d c #00ffff",
"c c #868686",
"b c #ffffff",
".........#######",
".........#######",
"abbbbbbba#a#####",
"abcccccba#aa####",
"abbbbbbba#ada###",
"abccaaaaaaadda##",
"abbbaddddddddda#",
"aaaaadddddddddda",
"####addddddddda#",
"####aaaaaaadda##",
"##########ada###",
"##########aa####",
"##########a#####",
"################",
"################",
"################"};

/* XPM */
static const char *Std_WindowPrev[]={
"16 16 6 1",
". c None",
"a c #000000",
"# c #000080",
"d c #00ffff",
"c c #868686",
"b c #ffffff",
"................",
".......#########",
".......#########",
".....a.abbbbbbba",
"....aa.abcccccba",
"...ada.abbbbbbba",
"..addaaaaaaaccba",
".adddddddddabbba",
"addddddddddaaaaa",
".addddddddda....",
"..addaaaaaaa....",
"...ada..........",
"....aa..........",
".....a..........",
"................",
"................"};

/* XPM */
static const char *Std_WindowTileHor[]={
"16 16 3 1",
". c None",
"# c #000080",
"a c #ffffff",
"................",
".#############..",
".#a###########..",
".#############..",
".#aaaaaaaaaaa#..",
".#aaaaaaaaaaa#..",
".#aaaaaaaaaaa#..",
".#############..",
".#a###########..",
".#############..",
".#aaaaaaaaaaa#..",
".#aaaaaaaaaaa#..",
".#aaaaaaaaaaa#..",
".#############..",
"................",
"................"};

/* XPM */
static const char *Std_WindowTileVer[]={
"16 16 3 1",
". c None",
"# c #000080",
"a c #ffffff",
"................",
".#############..",
".#a#####a#####..",
".#############..",
".#aaaaa#aaaaa#..",
".#aaaaa#aaaaa#..",
".#aaaaa#aaaaa#..",
".#aaaaa#aaaaa#..",
".#aaaaa#aaaaa#..",
".#aaaaa#aaaaa#..",
".#aaaaa#aaaaa#..",
".#aaaaa#aaaaa#..",
".#aaaaa#aaaaa#..",
".#############..",
"................",
"................"};

/* XPM */
static const char *Test1[]={
"16 16 2 1",
". c None",
"# c #000000",
"................",
"##########......",
"##########.#....",
"....##....##....",
"....##...###....",
"....##..####....",
"....##..#.##....",
"....##....##....",
"....##....##....",
"....##....##....",
"....##....##....",
"....##....##....",
"....##....##....",
"....##....##....",
"....##....##....",
"................"};

/* XPM */
static const char *Test2[]={
"16 16 2 1",
". c None",
"# c #000000",
"................",
"##########......",
"##########......",
"....##..........",
"....##...####...",
"....##...#####..",
"....##..##...#..",
"....##.......#..",
"....##.......#..",
"....##......##..",
"....##.....##...",
"....##....##....",
"....##...##.....",
"....##..######..",
"....##..######..",
"................"};

/* XPM */
static const char *TileHorizontal[]={
"16 16 3 1",
"# c #0000ff",
". c #d6d3ce",
"a c #ffffff",
"................",
".##############.",
".##############.",
".#aaaaa##aaaaa#.",
".#aaaaa##aaaaa#.",
".#aaaaa##aaaaa#.",
".#aaaaa##aaaaa#.",
".#aaaaa##aaaaa#.",
".#aaaaa##aaaaa#.",
".#aaaaa##aaaaa#.",
".#aaaaa##aaaaa#.",
".#aaaaa##aaaaa#.",
".#aaaaa##aaaaa#.",
".#aaaaa##aaaaa#.",
".##############.",
"................"};

/* XPM */
static const char *TileVertical[]={
"16 16 3 1",
"# c #000084",
". c #d6d3ce",
"a c #ffffff",
"................",
".##############.",
".##############.",
".#aaaaaaaaaaaa#.",
".#aaaaaaaaaaaa#.",
".#aaaaaaaaaaaa#.",
".#aaaaaaaaaaaa#.",
".##############.",
".#a############.",
".##############.",
".#aaaaaaaaaaaa#.",
".#aaaaaaaaaaaa#.",
".#aaaaaaaaaaaa#.",
".#aaaaaaaaaaaa#.",
".##############.",
"................"};

/* XPM */
static const char *tool_color[]={
"16 15 11 1",
"# c #000000",
"e c #0000ff",
"h c #008284",
"d c #00ff00",
"f c #00ffff",
"g c #840000",
"i c #848284",
". c #c6c3c6",
"a c #ff0000",
"c c #ff00ff",
"b c #ffff00",
"................",
".#############..",
".#aaa#bbb#ccc#..",
".#aaa#bbb#ccc#..",
".#aaa#bbb#ccc#..",
".#############..",
".#ddd#eee#fff#..",
".#ddd#eee#fff#..",
".#ddd#eee#fff#..",
".#############..",
".#ggg#hhh#bbi#..",
".#ggg#hhh#bbi#..",
".#ggg#hhh#bbi#..",
".#############..",
"................"};

/* XPM */
static const char *tool_delete[]={
"16 15 6 1",
"b c #000000",
"d c #008200",
"# c #848284",
"a c #c6c3c6",
". c #ff0000",
"c c #ffff00",
"....####........",
"..##a#####......",
"##aa#baaac##....",
"#aa##b#aaacc##..",
"#aa##b##aaaa#ab.",
"#aaaa###aaaa##b.",
".#aaaddcaca###b.",
".#aadaadda####b.",
".#adddadda###b..",
".#aadaaaaa###b..",
"..#adadada###b..",
"..#aadddda###b..",
"..bbaadaaa##b...",
"....bbaaa###b...",
"......bbaa##b..."};

/* XPM */
static const char *tool_material[]={
"16 15 3 1",
". c #c6c3c6",
"a c #ff0000",
"# c #ffff00",
"................",
".......######...",
"......#......#..",
".....#........#.",
".....##......#..",
"....a.#######a..",
"....aa#aaaaaaa..",
"aaaaaaa#aaaaaa..",
"aaaaaaa#aaaaaa..",
"....aa#aaaaaaa..",
"....a.#######a..",
".....##......#..",
".....#........#.",
"......#......#..",
".......######..."};

/* XPM */
static const char *tool_shading[]={
"16 15 3 1",
"# c #848284",
". c #c6c3c6",
"a c #ffff00",
"................",
".....######.....",
"....#aaaaaa#....",
"...#aaaaaaaa#...",
"...##aaaaaa##...",
"...#a######a#...",
"...#aaaaaaaa#...",
"...#aaaaaaaa#...",
"...#aaaaaaaa#...",
"...#aaaaaaaa#...",
"...#aaaaaaaa#...",
"...#aaaaaaaa#...",
"...#aaaaaaaa#...",
"....#aaaaaa#....",
".....######....."};

/* XPM */
static const char *tool_transparency[]={
"16 15 3 1",
"# c #848284",
". c #c6c3c6",
"a c #ffff00",
"................",
".....######.....",
"....#a.a.a.#....",
"...#a.a.a.aa#...",
"...##a.a.a.##...",
"...#a######.#...",
"...#.a.a.a.a#...",
"...#a.a.a.a.#...",
"...#.a.a.a.a#...",
"...#a.a.a.a.#...",
"...#.######a#...",
"...##a.a.a.##...",
"...#a.a.a.a.#...",
"....#a.a.a.#....",
".....######....."};

/* XPM */
static const char *tool_wireframe[]={
"16 15 3 1",
". c #c6c3c6",
"# c #ffff00",
"a c #ffffff",
"................",
".....######.....",
"....#......#....",
"...#........#...",
"...##......#a...",
"...#.######.a...",
"...#........a...",
"...#........a...",
"...#........a...",
"...#........a...",
"...#.######.a...",
"...##......#a...",
"...#........#...",
"....#......#....",
".....######....."};

/* XPM */
static const char *TopLevel[]={
"16 16 4 1",
". c #000084",
"# c #848284",
"a c #d6d3ce",
"b c #ffffff",
"................",
".##############.",
"................",
".........a......",
".........a......",
".bbbbbbb.a.####.",
".bbbbbbb.a.####.",
".bbbbbbb.a.####.",
".bbbbbbb.a......",
".bbbbbbb.aaaaaaa",
".bbbbbbb.a......",
".bbbbbbb.a.####.",
".bbbbbbb.a.####.",
".bbbbbbb.a.####.",
".........a......",
"aaaaaaaaaaaaaaaa"};

/* XPM */
static const char *Undo[]={
"22 22 85 2",
".# c None",
".o c None",
"#h c None",
"#p c None",
".a c None",
".M c None",
"#n c None",
"#m c None",
"#k c None",
"Qt c None",
".f c #000000",
".c c #050505",
"#s c #0d0d0d",
"#j c #171717",
"#r c #222222",
"#e c #272727",
".n c #2e2e2e",
"#q c #2f2f2f",
"#o c #343434",
".8 c #3d0000",
".j c #404040",
"#l c #454545",
".9 c #4b0000",
"#i c #4b1717",
"#a c #4d0000",
".m c #4e4e4e",
".5 c #520000",
".V c #540000",
".S c #560000",
"#. c #5f0000",
".l c #606060",
".k c #666666",
".b c #767676",
".i c #7d1212",
"#f c #831a1a",
"#b c #860000",
".E c #880000",
".N c #885050",
"#g c #8a0000",
".F c #8a8a8a",
".d c #8d8d8d",
".e c #a56262",
".6 c #a60000",
"#d c #a80000",
".x c #a91f1f",
".W c #aa0000",
".L c #ad0000",
".1 c #b00000",
"#c c #b03636",
".G c #b07c7c",
".0 c #b10000",
".y c #b27e7e",
".p c #b37e7e",
".7 c #b40000",
".g c #b47e7e",
".U c #b50000",
".Z c #b80000",
".R c #ba0000",
".2 c #bd0000",
".O c #c33b3b",
".3 c #c90000",
".4 c #cd0000",
".Y c #ce0000",
"## c #d91010",
".X c #dd0000",
".T c #e30000",
".w c #e33b3b",
".Q c #e80000",
".P c #ea2020",
".K c #ec0000",
".J c #ee0000",
".D c #ef0000",
".I c #ef2222",
".B c #f20000",
".C c #f20303",
".H c #f25151",
".A c #f32222",
".z c #f55151",
".s c #f61010",
".r c #f72222",
".t c #f83434",
".v c #f84040",
".u c #f84343",
".q c #f85151",
".h c #fa4545",
"QtQtQtQtQtQtQtQt.#.#.#QtQtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQtQt.#.#.a.#.#.#QtQtQtQtQtQtQtQtQtQt",
"QtQtQtQtQt.#.#.b.c.#.#.#QtQtQtQtQtQtQtQtQtQt",
"QtQtQtQt.#.#.d.e.f.#.#.#.#.#.#.#.#.#.#.#QtQt",
"QtQtQt.#.#.d.g.h.i.j.k.k.k.k.l.m.n.o.#.#.#Qt",
"QtQt.#.#.d.p.q.r.s.t.u.u.u.u.v.w.x.f.#.#.#.#",
"Qt.#.#.d.y.z.A.B.B.B.B.B.B.B.B.C.D.E.f.#.#.#",
"Qt.#.F.G.H.I.J.J.J.J.J.J.J.J.J.J.K.L.f.#.#.#",
".#.M.N.O.P.Q.Q.Q.Q.Q.Q.Q.Q.Q.Q.Q.Q.R.f.#.#.#",
".#.#.#.S.L.T.T.T.T.T.T.T.T.T.T.T.T.U.f.#.#.#",
".#.#.#.#.V.W.X.Y.Z.0.1.1.2.3.R.4.X.0.f.#.#.#",
"Qt.#.#.#.#.5.6.7.8.f.f.f.f.9#..f##.L.f.#.#.#",
"QtQt.#.#.#.##a#b.f.#.#.#.#.f.f.f#c#d.f.#.#.#",
"QtQtQt.#.#.#.#.f.f.#.#.#.#.#.##e#f#g.f.#.#.#",
"QtQtQtQt.#.#.#.#.f.#.#.#.#.#.##h#i.f.f.#.#.#",
"QtQtQtQtQt.#.#.#.#.#.#.#Qt.#.#.k#j.f.#.#.#.#",
"QtQtQtQtQtQt.#.#.#.#.#.#.#.##k#l.f.f.#.#.#.#",
"QtQtQtQt.#.#.#.#.#.#.#.##m#n#o.f.f.#.#.#.#.#",
"QtQtQtQt#p#q#r#s.f.f.f.f.f.f.f.#.#.#.#.#.#Qt",
"QtQtQt.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#QtQt",
"QtQtQtQt.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#QtQtQt",
"QtQtQtQt.#.#.#.#.#.#.#.#.#.#.#.#.#.#QtQtQtQt"};

/* XPM *//*
static const char *Undo[]={
"24 24 9 1",
". c None",
"b c #000000",
"# c #299663",
"c c #29cb94",
"a c #29ff94",
"g c #adaead",
"e c #cecfe7",
"d c #ceff94",
"f c #ffffff",
"........................",
"........................",
"........................",
"........................",
".............#####......",
"...........##aaaaab.....",
"...#.....##aaccccacb....",
"...#b...#aaccbbbbcacb...",
"...#dbe#aacbb....#acb...",
"...#fdbaacb......#acb...",
"...#dfdacb.......#acb...",
"...#fdacbe.......#acb...",
"...#daaacb.......#acb...",
"...#ccccccb.....#acb....",
"...bbbbbbbbb....#acb....",
"...............#acb.....",
"...............#acb.....",
"..............gbbb......",
".e......................",
"........................",
"........................",
"........................",
"........................",
"........................"};
*/
/* XPM */
static const char *view_axo[]={
"20 20 4 1",
"# c #000000",
"a c #00ffff",
". c None",
"b c #ffff00",
"....................",
"....................",
".........##.........",
"........#.a##.......",
".......#..a..##.....",
"......#...a....##...",
".....##...a....##...",
".....#.##.a...#.#...",
".....#...##..#..#...",
"..b..#...aa##...#...",
".bbb.#bba..a#...#...",
"..b..#ba....#aa.#...",
"..b..#a.....#..a#...",
"..b.b##.....#..#....",
"..bb...##...#.#.....",
"...bbbbb.##.##......",
"......bb...##.......",
".....bbb............",
"....................",
"...................."};

/* XPM */
static const char *view_back[]={
"16 16 5 1",
". c None",
"c c #00ffff",
"a c #840000",
"b c #848284",
"# c #ffff00",
".............#..",
"............#...",
"...........#....",
"....aaaaaaaaaa..",
"...ba.#..#..ba..",
"..b.a.#.#..b.a..",
".bbbab##bbb..a..",
".b..a.####b..a..",
".b..a.....b..a..",
".b..a.....b..a..",
".b..a.....b..a..",
".b..a.....b..a..",
".b..aaaaaaaaaa..",
".b.c......b.b...",
".bc.......bb....",
".bbbbbbbbbb....."};

/* XPM */
static const char *view_bottom[]={
"16 16 5 1",
". c None",
"a c #00ffff",
"b c #840000",
"# c #848284",
"c c #ffff00",
"....##########..",
"...#a.......##..",
"..#.a......#.#..",
".##########..#..",
".#..a.....#..#..",
".#..a.....#..#..",
".#..a.....#..#..",
".#..a.....#..#..",
".#..a.....#..#..",
".#..bbbbbbbbbb..",
".#.b...c..#.b...",
".#b...ccc.bb....",
".bbbbbbbbbb.....",
".....c.c.c......",
".......c........",
".......c........"};

/* XPM */
static const char *view_comp_off[]={
"16 16 3 1",
". c None",
"# c #000000",
"a c #848284",
"................",
"................",
".....#########..",
"....#a......##..",
"...#.a.....#.#..",
"..#########..#..",
"..#..a....#..#..",
"..#..a....#..#..",
"..#..a....#..#..",
"..#..a....#..#..",
"..#..aaaaa#aa#..",
"..#.a.....#.#...",
"..#a......##....",
"..#########.....",
"................",
"................"};

/* XPM */
static const char *view_comp_on[]={
"16 16 2 1",
". c None",
"# c #000000",
"................",
"................",
".....#########..",
"....#.......##..",
"...#.......#.#..",
"..#########..#..",
"..#.......#..#..",
"..#.......#..#..",
"..#.......#..#..",
"..#.......#..#..",
"..#.......#..#..",
"..#.......#.#...",
"..#.......##....",
"..#########.....",
"................",
"................"};

/* XPM */
static const char *view_fitall[]={
"16 16 5 1",
"# c None",
"b c #000000",
"c c #848200",
"a c #848284",
". c #ffff00",
"...##########...",
"..#####aaaaa##..",
".#.###a#####a.#.",
"###.#a#######a##",
"####aa#######aa#",
"####a#########a#",
"####a#########a#",
"####aa#######aa#",
"#####a#######a##",
"#####ab#####a###",
"####bb#aaaaa####",
"###bb###########",
"##cb########.###",
".ac##########.#.",
"..############..",
"...##########..."};

/* XPM */
static const char *view_fitarea[]={
"16 16 4 1",
". c None",
"b c #000000",
"a c #848284",
"# c #ffff00",
".#..............",
"###aaaa.aaaaaab.",
".#.....a....a.a.",
".a....a......aa.",
".a...aa......aa.",
".a...a........a.",
".a...a........a.",
".a...aa......aa.",
".a....a......aa.",
".a....ab....a.a.",
".a...bb.aaaa..a.",
"....bb........a.",
"...bb.........a.",
"..bb..........#.",
"..a...aaaaaaa###",
"..............#."};

/* XPM */
static const char *view_front[]={
"16 16 5 1",
". c None",
"a c #00ffff",
"b c #840000",
"# c #848284",
"c c #ffff00",
"................",
"................",
"....##########..",
"...#a.......##..",
"..#.a......#.#..",
".bbbbbbbbbb..#..",
".b..a.....b..#..",
".b..a.....b..#..",
".b..a.....b..#..",
".b..ccc...b..#..",
".b...cc...b..#..",
".b..c.caaabaa#..",
".b.c......b.#...",
".bc.......b#....",
".cbbbbbbbbb.....",
"................"};

/* XPM */
static const char *view_glpan[]={
"16 16 4 1",
". c None",
"b c #000000",
"a c #848284",
"# c #ffff00",
"................",
".......#........",
"......###.......",
".....#.#.#......",
".......#........",
"....aaa#.aaa....",
"..#.a..#...a#...",
".#..a......a.#..",
"######....#####.",
".#..a......a.#..",
"..#.a..#...a#...",
"....baa#.aaa....",
".......#........",
".....#.#.#......",
"......###.......",
".......#........"};

/* XPM */
static const char *view_left[]={
"16 16 5 1",
". c None",
"c c #00ffff",
"# c #840000",
"a c #848284",
"b c #ffff00",
"................",
"................",
"......#aaaaaaaaa",
".....##.......aa",
"....#.#......a.a",
"...#aa#aaaaaa..a",
"..b#..#.....a..a",
"...#b.#.....a..a",
"bbb#bb#.....a..a",
"...#b.#.....a..a",
"..b#..#.....a..a",
"...#..#cccccacca",
"...#.#......a.a.",
"...##.......aa..",
"...#aaaaaaaaa...",
"................"};

/* XPM */
static const char *view_pan[]={
"16 16 2 1",
". c None",
"# c #ffff00",
".......#........",
"......###.......",
".....#.#.#......",
".......#........",
".......#........",
"..#....#....#...",
".#...........#..",
"#####.....#####.",
".#...........#..",
"..#.........#...",
".......#........",
".......#........",
".....#.#.#......",
"......###.......",
".......#........",
"................"};

/* XPM */
static const char *view_reset[]={
"16 16 3 1",
". c None",
"# c #000000",
"a c #ffff00",
"................",
".........#......",
"........###.###.",
".........#...##.",
".........#..#.#.",
".........#.#....",
".........##..#..",
"..........#####.",
"..aaa........#..",
".aa.aa..........",
".aa.aa..........",
".aa.aa..........",
".aa.aa..........",
"..aaa...........",
"................",
"................"};

/* XPM */
static const char *view_right[]={
"16 16 6 1",
". c None",
"d c #000000",
"b c #00ffff",
"a c #840000",
"# c #848284",
"c c #ffff00",
"................",
"................",
"...#########a...",
"..#b.......aa...",
".#.b......a.a...",
"#########a..c...",
"#..b.....a.ca...",
"#..b.....acccccc",
"#..b.....a.ca...",
"#..b.....a..c...",
"#..b.....a..a...",
"#..bbbbbbdbba...",
"#.b......a.a....",
"#b.......aa.....",
"#########a......",
"................"};

/* XPM */
static const char *view_rotate[]={
"16 16 4 1",
". c None",
"a c #000000",
"# c #848284",
"b c #ffff00",
"....#...........",
"...##...........",
"..#a###.........",
"..a###.a##......",
"bbb..##.#.##...b",
".....#...#.a.bbb",
"....#....#..#...",
"....#...b.#.#...",
"....#bb...###...",
"..bbb#....##....",
"bb...##..#a#....",
".......####.....",
".........##.....",
"......b..#......",
".....bbb#.......",
"......b........."};

/* XPM */
static const char *view_top[]={
"16 16 5 1",
". c None",
"b c #00ffff",
"a c #840000",
"c c #848284",
"# c #ffff00",
".......#........",
".......#........",
".....#.#.#......",
"....aa###aaaaa..",
"...ab..#....ac..",
"..a.b......a.c..",
".aaaaaaaaaa..c..",
".c..b.....c..c..",
".c..b.....c..c..",
".c..b.....c..c..",
".c..b.....c..c..",
".c..b.....c..c..",
".c..bbbbbbcbbc..",
".c.b......c.c...",
".cb.......cc....",
".cccccccccc....."};

/* XPM */
static const char *view_zoom[]={
"16 16 5 1",
". c None",
"c c #000000",
"b c #848200",
"# c #848284",
"a c #ffff00",
"................",
"......#####.....",
"aaa..#.....#....",
"....#.......#...",
"....#.......##..",
"...#..aa.....#..",
"...#....aaa..#..",
"...##.......b#..",
"....#.......#...",
"....#c.....#..a.",
"...cc.#####..aaa",
"..cc..........a.",
".cc.............",
"cc..............",
"#...............",
"................"};

/* XPM */
static const char *WhatsThis2[]={
"24 24 7 1",
". c None",
"d c #009ea5",
"a c #181052",
"b c #399ea5",
"e c #a5a2a5",
"# c #cecfe7",
"c c #ffff94",
"........................",
"........................",
".......................#",
".............aaaaaa....#",
"..baa....###aaaaaaaa....",
"..baca....#aaaaddaaaa...",
"..bacca....aaad...aaad..",
"..baccca...aaad...aaad..",
"..bacccca...ddd..aaaad..",
"..baccccca.....#aaaad...",
"..bacccccca....aaaad....",
"..baccccccca..aaaad.....",
"..bacccccccca#aaad......",
"..bacccccaaa..aaad......",
"..baccacca#...#ddd......",
"..bacabacca...aaad......",
"...babbaccae..aaad......",
".......bacca..aaad......",
".......bacca...ddd......",
"........baa.............",
"........................",
"........................",
"........................",
"........................"};

static const char * WhatsThis[] = {
"24 24 3 1",
"	c None",
"o	c #000000",
"a	c #000080",
"........................",
"........................",
"........................",
"........................",
"....o        aaaaa      ",
"....oo      aaa aaa     ",
"....ooo    aaa   aaa    ",
"....oooo   aa     aa    ",
"....ooooo  aa     aa    ",
"....oooooo  a    aaa    ",
"....ooooooo     aaa     ",
"....oooooooo   aaa      ",
"....ooooooooo aaa       ",
"....ooooo     aaa       ",
"....oo ooo              ",
"....o  ooo    aaa       ",
"....    ooo   aaa       ",
"....    ooo             ",
"....     ooo            ",
"....     ooo            ",
"........................",
"........................",
"........................",
"........................"};

/*XPM*/
const char* Folder32[] = { 
"32 32 10 1",
". c None",
"# c #000000",
"b c #00c300",
"e c #313031",
"h c #420000",
"d c #5a595a",
"g c #a5a2a5",
"f c #c6c3c6",
"a c #c6ffc6",
"c c #ffffff",
"...###..........................",
"...#aa##........................",
".###baaa##......................",
".#cd##baaa##....................",
".#cccd##baaa##..##e.............",
".#cccccd##baaa##aaa##...........",
".#cccccccd##baaaaaaaa##.........",
".#cccccccccd##baaaaaaa#.........",
".#cccccfcffgg#bbbbaaaaa#........",
".#ccccccfcfffd#bbbbbbaa#........",
".#cccfcfcfcffgd##bh#bbba#.......",
".#ccccfcfffffffgd#dd##ba#.......",
".#cfcfcfcfffffffffgfgd#bb#......",
".#ccfcfffffffffgfgfgfgd#b#......",
".#cfcfcfffffffffgfgfggd#b#......",
".#fcfffffffffgfgfgggggd#b#......",
".#cfcfffffffffgfgfggggd#b#......",
".#fffffffffgfgfgggggggdhb#......",
".#ffffffffffgfgfggggggd#b#......",
".#ggfffffgfgfgggggggggd#b#......",
".#ddggffffgfgfggggggggd#b#......",
"..##ddggfgfgggggggggggd#b#......",
"....##ddgggfggggggggggd#b#......",
"......##ddggggggggggggd#b#......",
"........##ddggggggggggd#b#......",
"..........##ddggggggggd#b#......",
"............##ddggggggd#b###....",
"..............##ddggggd#b#####..",
"................##ddggd#b######.",
"..................##ddd#b#####..",
"....................##d#b###....",
"......................####......"};

/* XPM */
const char* MacroEditor[] = {
"12 16 6 1",
" 	c #040404",
".	c None",
"X	c white",
"o	c #808304",
"O	c black",
"+	c #f3f7f3",
"       .....",
" XXXXX  ....",
" XXXXX X ...",
" XXXXX XX ..",
" XooXX    O.",
" X+XXX+XXXO.",
" XXXXXXXXXO.",
" XoooXooXXO.",
" XXXXXXXXXO.",
" XXXXXXXXXO.",
" XoXXoooXXO.",
" XXXXXXXXXO.",
"OXXXXXXXXXO.",
"OXXXXXXXXXO.",
"OOOOOOOOOOO.",
"............"};
