const char FreeCADInit[] ="# FreeCAD init module\n"
"# (c) 2001 Jürgen Riegel\n"
"#\n"
"# Gathering all the information to start FreeCAD\n"
"# This is the second one of three init scripts, the third one\n"
"# runs when the gui is up\n"
"\n"
"#***************************************************************************\n"
"#*   (c) Jürgen Riegel (juergen.riegel@web.de) 2002                        *\n"
"#*                                                                         *\n"
"#*   This file is part of the FreeCAD CAx development system.              *\n"
"#*                                                                         *\n"
"#*   This program is free software; you can redistribute it and/or modify  *\n"
"#*   it under the terms of the GNU General Public License (GPL)            *\n"
"#*   as published by the Free Software Foundation; either version 2 of     *\n"
"#*   the License, or (at your option) any later version.                   *\n"
"#*   for detail see the LICENCE text file.                                 *\n"
"#*                                                                         *\n"
"#*   FreeCAD is distributed in the hope that it will be useful,            *\n"
"#*   but WITHOUT ANY WARRANTY; without even the implied warranty of        *\n"
"#*   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *\n"
"#*   GNU Library General Public License for more details.                  *\n"
"#*                                                                         *\n"
"#*   You should have received a copy of the GNU Library General Public     *\n"
"#*   License along with FreeCAD; if not, write to the Free Software        *\n"
"#*   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  *\n"
"#*   USA                                                                   *\n"
"#*                                                                         *\n"
"#*   Juergen Riegel 2002                                                   *\n"
"#***************************************************************************/\n"
"\n"
"\n"
"# imports the one and only\n"
"import FreeCAD\n"
"\n"
"try:\n"
"	import sys,os,dircache\n"
"except:\n"
"	FreeCAD.PrintError(\"\\n\\nSeems the python standard libs are not installed, bailing out!\\n\\n\")\n"
"	raise\n"
"\n"
"def InitDocumentation():\n"
"	# Checking on FreeCAD documentation path ++++++++++++++++++++++++++++++++++++++++++\n"
"	if os.path.isdir(FreeCAD.ConfigGet(\"HomePath\")+\'Doc\'):\n"
"		if os.path.isdir(FreeCAD.ConfigGet(\"HomePath\")+\'Doc\\\\free-cad.sourceforge.net\'):\n"
"			FreeCAD.ConfigSet(\"DocPath\",FreeCAD.ConfigGet(\"HomePath\")+\'Doc\\\\free-cad.sourceforge.net\')\n"
"\n"
"\n"
"def InitApplications():\n"
"	# Checking on FreeCAD Module path ++++++++++++++++++++++++++++++++++++++++++\n"
"	ModDir = FreeCAD.ConfigGet(\"HomePath\")+\'src/Mod\'\n"
"	#print FreeCAD.ConfigGet(\"HomePath\")\n"
"	if os.path.isdir(FreeCAD.ConfigGet(\"HomePath\")+\'Mod\'):\n"
"		ModDir = FreeCAD.ConfigGet(\"HomePath\")+\'Mod\'\n"
"	else:\n"
"		if os.path.isdir(FreeCAD.ConfigGet(\"HomePath\")+\'src\\\\Mod\'):\n"
"			ModDir = FreeCAD.ConfigGet(\"HomePath\")+\'src\\\\Mod\'\n"
"	sys.path.append( \'..\\\\bin\' )\n"
"	sys.path.append( ModDir )\n"
"	if os.path.isdir(FreeCAD.ConfigGet(\"HomePath\")+\'src\\\\Tools\'):\n"
"		sys.path.append( FreeCAD.ConfigGet(\"HomePath\")+\'src\\\\Tools\' )\n"
"	Log(\"   Using \"+ModDir+\" as module path!\\n\")\n"
"	# Searching modules dirs +++++++++++++++++++++++++++++++++++++++++++++++++++\n"
"	ModDirs = dircache.listdir(ModDir)\n"
"	PathExtension = \"\"\n"
"	#print ModDirs\n"
"	Log(\'Init:   Searching modules...\\n\')\n"
"	ModPar = App.ParamGet(\"System parameter:Modules\")\n"
"	for Dir in ModDirs:\n"
"		if ( (Dir != \'CVS\') & (Dir != \'__init__.py\')):\n"
"			Log(\'Init:      Initializing: \' + Dir + \'... \')\n"
"			ModGrp = ModPar.GetGroup(Dir)\n"
"			sys.path.append( os.path.join(ModDir,Dir) )\n"
"			PathExtension += \";\" + os.path.join(ModDir,Dir)\n"
"			InstallFile = os.path.join(os.path.join(ModDir,Dir),\"Init.py\")\n"
"			if ( os.path.exists(InstallFile) ):\n"
"				try:\n"
"					execfile(InstallFile)\n"
"				except:\n"
"					Err(\"Unexpected error in : \" + InstallFile + \" not initialized!\\n\")\n"
"				else:\n"
"					Log(\'Init:        done\\n\')\n"
"			else:\n"
"				Wrn(\"Init.py not found! \"+Dir+\" not initialized!\\n\")\n"
"	os.environ[\"PATH\"] += PathExtension\n"
"	#Log(\"PATH after addition: \" + os.environ[\"PATH\"] + \"\\n\")\n"
"	#Log(\"path extension: \" + PathExtension + \"\\n\")\n"
"\n"
"#			else:\n"
"#				FreeCAD.PrintMessage(\'new! install it...\\n\')\n"
"#				InstallFile = os.path.join(os.path.join(ModDir,Dir),\"Install.py\")\n"
"#				if ( os.path.exists(InstallFile) ):\n"
"#					execfile(InstallFile)\n"
"#				else:\n"
"#					Wrn(\"         Install.py not found! \"+Dir+\" not installed!\\n\")\n"
"\n"
"\n"
"# some often used shortcuts (for lazy people like me ;-)\n"
"App = FreeCAD\n"
"Log = FreeCAD.PrintLog\n"
"Msg = FreeCAD.PrintMessage\n"
"Err = FreeCAD.PrintError\n"
"Wrn = FreeCAD.PrintWarning\n"
"\n"
"Log (\'\\nInit: starting App::FreeCADInit.py\\n\')\n"
"\n"
"# init every application by importing Init.py\n"
"InitApplications()\n"
"\n"
"FreeCAD.EndingAdd(\"FCStd\",\"FreeCAD\")\n"
"\n"
"# set to no gui, is overwriten by InitGui\n"
"App.GuiUp = 0\n"
"\n"
"Log (\'\\nInit: App::FreeCADInit.py done\\n\')\n"
"\n"
"\n"
"\n"
"\n"
;


