const char FreeCADTest[] ="# FreeCAD test module\n"
"# (c) 2002 Jürgen Riegel\n"
"#\n"
"# Testing the function of the base system and run\n"
"# (if existing) the test function of the modules\n"
"#\n"
"\n"
"#***************************************************************************\n"
"#*   (c) Jürgen Riegel (juergen.riegel@web.de) 2002                        *\n"
"#*                                                                         *\n"
"#*   This file is part of the FreeCAD CAx development system.              *\n"
"#*                                                                         *\n"
"#*   This program is free software; you can redistribute it and/or modify  *\n"
"#*   it under the terms of the GNU General Public License (GPL)            *\n"
"#*   as published by the Free Software Foundation; either version 2 of     *\n"
"#*   the License, or (at your option) any later version.                   *\n"
"#*   for detail see the LICENCE text file.                                 *\n"
"#*                                                                         *\n"
"#*   FreeCAD is distributed in the hope that it will be useful,            *\n"
"#*   but WITHOUT ANY WARRANTY; without even the implied warranty of        *\n"
"#*   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *\n"
"#*   GNU Library General Public License for more details.                  *\n"
"#*                                                                         *\n"
"#*   You should have received a copy of the GNU Library General Public     *\n"
"#*   License along with FreeCAD; if not, write to the Free Software        *\n"
"#*   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  *\n"
"#*   USA                                                                   *\n"
"#*                                                                         *\n"
"#*   Juergen Riegel 2002                                                   *\n"
"#***************************************************************************/\n"
"\n"
"\n"
"Log (\"FreeCAD test running...\\n\\n\")\n"
"\n"
"TempPath = os.getenv(\'TEMP\')\n"
"if not TempPath: TempPath=\'.\'\n"
"Log (\'Using temp path: \' + TempPath + \'\\n\')\n"
"\n"
"# Basics +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++\n"
"FreeCAD.PrintLog (\"Testing console...\\n\")\n"
"\n"
"FreeCAD.PrintMessage(\"   Printing message\\n\")\n"
"FreeCAD.PrintError(\"   Printing error\\n\")\n"
"FreeCAD.PrintWarning(\"   Printing warning\\n\")\n"
"FreeCAD.PrintLog(\"   Printing Log\\n\")\n"
"\n"
"# Application and Document +++++++++++++++++++++++++++++++++++++++++++++++++\n"
"Log (\"Testing Application and Document...\\n\")\n"
"\n"
"Log(\"   Creating new Part document and filing up\\n\")\n"
"Doc = App.New(\"Part\")\n"
"i = Doc.UndoLimit\n"
"i = Doc.AvailableUndos\n"
"i = Doc.AvailableRedos\n"
"\n"
"Main = Doc.Main #getting the main label of the document\n"
"L1 = Main.GetLabel(1)\n"
"L1 = Main.GetLabel(1)\n"
"L1 = Main.GetLabel(1)\n"
"L1 = Main.GetLabel(1)\n"
"L1 = Main.GetLabel(1)\n"
"L1 = Main.GetLabel(1)\n"
"L2 = Main.GetLabel(2)\n"
"L3 = Main.GetLabel(3)\n"
"L4 = Main.GetLabel(4)\n"
"L5 = Main.GetLabel(5)\n"
"L6 = Main.GetLabel(6)\n"
"L7 = Main.GetLabel(7)\n"
"L1.Int = 1\n"
"L1.Real = 1.0\n"
"L1.Name = \"Hallo\"\n"
"\n"
"# saving and restoring\n"
"\n"
"SavePath = TempPath + os.sep + \"Test1.FCStd\"\n"
"Log(\"   Save and Open the document to: \" + SavePath + \"\\n\")\n"
"Doc.SaveAs(SavePath)\n"
"Log(\"provocate exceptio by try loading a already open document\\n\")\n"
"try:\n"
"    Doc2 = App.DocOpen(SavePath)\n"
"except:\n"
"    Log(\"exception thrown, OK\\n\")\n"
"else:\n"
"    Log(\"no exception thrown, ERROR\\n\")\n"
"    raise IOError\n"
"# closing doc\n"
"Doc = 0\n"
"\n"
"#Doc2 = App.DocOpen(SavePath)\n"
"\n"
"#Log(Doc2.Main.GetLabel(1).Name)\n"
"\n"
"\n"
"\n"
"FreeCAD.PrintLog (\"FreeCAD test done\\n\")\n"
"\n"
"\n"
;


