# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'User_Interface_Mach_Dist.ui'
#
# Created: Thu Jan 13 14:10:55 2011
#      by: PyQt4 UI code generator 4.7.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_dialog(object):
    def setupUi(self, dialog):
        dialog.setObjectName("dialog")
        dialog.resize(640, 480)
        dialog.setMinimumSize(QtCore.QSize(640, 480))
        self.gridLayout_8 = QtGui.QGridLayout(dialog)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.button_select_file = QtGui.QPushButton(dialog)
        self.button_select_file.setObjectName("button_select_file")
        self.verticalLayout.addWidget(self.button_select_file)
        self.button_select_output = QtGui.QPushButton(dialog)
        self.button_select_output.setObjectName("button_select_output")
        self.verticalLayout.addWidget(self.button_select_output)
        self.button_add_to_table = QtGui.QPushButton(dialog)
        self.button_add_to_table.setEnabled(False)
        self.button_add_to_table.setObjectName("button_add_to_table")
        self.verticalLayout.addWidget(self.button_add_to_table)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout_8.addLayout(self.verticalLayout, 0, 0, 2, 1)
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.groupBox_2 = QtGui.QGroupBox(dialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 2, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 2, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 1, 1, 1, 1)
        self.spinBox_z_level_from = QtGui.QSpinBox(self.groupBox_2)
        self.spinBox_z_level_from.setMinimumSize(QtCore.QSize(70, 20))
        self.spinBox_z_level_from.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.spinBox_z_level_from.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_z_level_from.setMinimum(-99)
        self.spinBox_z_level_from.setObjectName("spinBox_z_level_from")
        self.gridLayout_2.addWidget(self.spinBox_z_level_from, 0, 0, 1, 1)
        self.spinBox_z_level_to = QtGui.QSpinBox(self.groupBox_2)
        self.spinBox_z_level_to.setMinimumSize(QtCore.QSize(70, 20))
        self.spinBox_z_level_to.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_z_level_to.setMinimum(-99)
        self.spinBox_z_level_to.setObjectName("spinBox_z_level_to")
        self.gridLayout_2.addWidget(self.spinBox_z_level_to, 1, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(dialog)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 0, 2, 1, 1)
        self.spinBox_poisson_ratio = QtGui.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_poisson_ratio.sizePolicy().hasHeightForWidth())
        self.spinBox_poisson_ratio.setSizePolicy(sizePolicy)
        self.spinBox_poisson_ratio.setMinimumSize(QtCore.QSize(60, 20))
        self.spinBox_poisson_ratio.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_poisson_ratio.setSingleStep(0.1)
        self.spinBox_poisson_ratio.setProperty("value", 0.3)
        self.spinBox_poisson_ratio.setObjectName("spinBox_poisson_ratio")
        self.gridLayout_3.addWidget(self.spinBox_poisson_ratio, 1, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 1, 2, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 0, 1, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem4, 1, 1, 1, 1)
        self.spinBox_young_modulus = QtGui.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_young_modulus.sizePolicy().hasHeightForWidth())
        self.spinBox_young_modulus.setSizePolicy(sizePolicy)
        self.spinBox_young_modulus.setMinimumSize(QtCore.QSize(60, 20))
        self.spinBox_young_modulus.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_young_modulus.setMaximum(999.99)
        self.spinBox_young_modulus.setProperty("value", 210.0)
        self.spinBox_young_modulus.setObjectName("spinBox_young_modulus")
        self.gridLayout_3.addWidget(self.spinBox_young_modulus, 0, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox, 0, 1, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(dialog)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.spinBox_misalignment_x = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.spinBox_misalignment_x.setMinimumSize(QtCore.QSize(70, 20))
        self.spinBox_misalignment_x.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_misalignment_x.setDecimals(1)
        self.spinBox_misalignment_x.setMaximum(90.0)
        self.spinBox_misalignment_x.setProperty("value", 0.0)
        self.spinBox_misalignment_x.setObjectName("spinBox_misalignment_x")
        self.gridLayout.addWidget(self.spinBox_misalignment_x, 0, 0, 1, 1)
        self.label = QtGui.QLabel(self.groupBox_3)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 2, 1, 1)
        self.spinBox_misalignment_y = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.spinBox_misalignment_y.setMinimumSize(QtCore.QSize(43, 20))
        self.spinBox_misalignment_y.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_misalignment_y.setDecimals(1)
        self.spinBox_misalignment_y.setMaximum(90.0)
        self.spinBox_misalignment_y.setObjectName("spinBox_misalignment_y")
        self.gridLayout.addWidget(self.spinBox_misalignment_y, 1, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox_3)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 2, 1, 1)
        self.spinBox_misalignment_z = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.spinBox_misalignment_z.setMinimumSize(QtCore.QSize(43, 20))
        self.spinBox_misalignment_z.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_misalignment_z.setDecimals(1)
        self.spinBox_misalignment_z.setMaximum(90.0)
        self.spinBox_misalignment_z.setObjectName("spinBox_misalignment_z")
        self.gridLayout.addWidget(self.spinBox_misalignment_z, 2, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox_3)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 2, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 0, 1, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 1, 1, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem7, 2, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox_3, 1, 0, 1, 1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.check_fly_to_buy = QtGui.QCheckBox(dialog)
        self.check_fly_to_buy.setMinimumSize(QtCore.QSize(148, 18))
        self.check_fly_to_buy.setChecked(False)
        self.check_fly_to_buy.setObjectName("check_fly_to_buy")
        self.verticalLayout_2.addWidget(self.check_fly_to_buy)
        spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem8)
        self.gridLayout_7.addLayout(self.verticalLayout_2, 1, 1, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_7, 0, 1, 1, 1)
        spacerItem9 = QtGui.QSpacerItem(20, 56, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem9, 1, 1, 1, 1)
        self.button_dialog = QtGui.QDialogButtonBox(dialog)
        self.button_dialog.setOrientation(QtCore.Qt.Horizontal)
        self.button_dialog.setStandardButtons(QtGui.QDialogButtonBox.Close|QtGui.QDialogButtonBox.Ok)
        self.button_dialog.setObjectName("button_dialog")
        self.gridLayout_8.addWidget(self.button_dialog, 4, 0, 1, 2)
        self.JobTable = QtGui.QTableWidget(dialog)
        self.JobTable.setRowCount(0)
        self.JobTable.setColumnCount(9)
        self.JobTable.setObjectName("JobTable")
        self.JobTable.setColumnCount(9)
        self.JobTable.setRowCount(0)
        self.gridLayout_8.addWidget(self.JobTable, 2, 0, 1, 2)
        self.button_start_calculation = QtGui.QPushButton(dialog)
        self.button_start_calculation.setEnabled(False)
        self.button_start_calculation.setObjectName("button_start_calculation")
        self.gridLayout_8.addWidget(self.button_start_calculation, 3, 0, 1, 1)

        self.retranslateUi(dialog)
        QtCore.QMetaObject.connectSlotsByName(dialog)

    def retranslateUi(self, dialog):
        dialog.setWindowTitle(QtGui.QApplication.translate("dialog", "Machining Distortion Prediction", None, QtGui.QApplication.UnicodeUTF8))
        self.button_select_file.setText(QtGui.QApplication.translate("dialog", "Select Nastran Geometry File", None, QtGui.QApplication.UnicodeUTF8))
        self.button_select_output.setText(QtGui.QApplication.translate("dialog", "Select Output Folder", None, QtGui.QApplication.UnicodeUTF8))
        self.button_add_to_table.setText(QtGui.QApplication.translate("dialog", "Add Job", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("dialog", "Z-Level Offsets", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("dialog", "From", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("dialog", "To", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("dialog", "Material Properties", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("dialog", "Young Modulus [GPa]", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("dialog", "Poisson Ratio", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("dialog", "Set User Defined Misalignment", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("dialog", "Angle X-Axis", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("dialog", "Angle Y-Axis", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("dialog", "Angle Z-Axis", None, QtGui.QApplication.UnicodeUTF8))
        self.check_fly_to_buy.setText(QtGui.QApplication.translate("dialog", "Calculate Buy to Fly Ratio", None, QtGui.QApplication.UnicodeUTF8))
        self.button_start_calculation.setText(QtGui.QApplication.translate("dialog", "Start Calculation", None, QtGui.QApplication.UnicodeUTF8))

