
# libs needed ------------------------------------------
QTDIR    =/usr/lib/qt-2.2.3
OCCDIR   =/cygdrive/e/Develop/Libs/Cas5.0/ros
PYTHONDIR=/cygdrive/e/Develop/Python2.1.1
XERCESDIR=/cygdrive/e/Develop/Libs/xerces-c2_2_0-win32


# config -----------------------------------------------
CFLAGS_D   = -g -Wall -D__DEBUG__ -DCYGWIN
CFLAGS_O   = -O2  -DCYGWIN 
CFLAGS     = $(CFLAGS_D)
CXXFLAGS_D = -g -Wall -D__DEBUG__ -DCYGWIN -DSIZEOF_LONG=4
CXXFLAGS_O = -O2 -DCYGWIN 
CXXFLAGS   = $(CXXFLAGS_D)


# progs needed -----------------------------------------
CC      = gcc
CPP	= g++
DEP     = Makefile
MOC     = $(QTDIR)/bin/moc
UIC     = $(QTDIR)/bin/uic

# include ---------------------------------------------

INCLUDE = -I$(QTDIR)/include -I$(OCCDIR)/inc -I$(PYTHONDIR)/include -I$(XERCESDIR)/include
  
# rules  ---------------------------------------------
.SUFFIXES: .c .cpp .o .moc
.c.o: Makefile
	$(CC) $(CFLAGS) $(INCLUDE) -c $< 

.cpp.o: Makefile
	$(CPP) $(CXXFLAGS) $(INCLUDE) -c $< 

.C.o: Makefile
	$(CPP) $(CXXFLAGS) $(INCLUDE) -c $< 

.h.moc: Makefile
	$(MOC) $<  -o $@ 

#standard -------------------------------------------

depends: $(SOURCES)
	$(CPP) -M $(CXXFLAGS) $(INCLUDE) $(SOURCES) > depends











