

#include "PreCompiled.h"
#include "Writer.h"
#include "Persistance.h"

// inclution of the generated files (generated By PersitancePy.xml)
#include "PersistancePy.h"
#include "PersistancePy.cpp"

using namespace Base;


Py::String PersistancePy::getContent(void) const
{
  Base::StringWriter writer;
  getPersistanceObject()->Save(writer);

  return  Py::String (writer.getString());
}

void  PersistancePy::setContent(Py::String arg)
{

}

Py::Int PersistancePy::getMemSize(void) const
{
  return Py::Int((long)getPersistanceObject()->getMemSize());
}


PyObject *PersistancePy::getCustomAttributes(const char* attr) const
{
  return 0;
}

int PersistancePy::setCustomAttributes(const char*,PyObject *obj)
{
  return 0; 
}

