

#include "PreCompiled.h"
#include "Writer.h"
#include "Persistance.h"

// inclution of the generated files (generated By PersitancePy.xml)
#include "PersistancePy.h"
#include "PersistancePy.cpp"

using namespace Base;

// returns a string which represent the object e.g. when printed in python
const char *PersistancePy::representation(void) const
{
    return "<persistence object>";
}


Py::String PersistancePy::getContent(void) const
{
    Base::StringWriter writer;
    getPersistanceObject()->Save(writer);

    return  Py::String (writer.getString());
}

void  PersistancePy::setContent(Py::String arg)
{
    throw Py::AttributeError(std::string("Attribute 'Content' of object 'Persistence' is read-only"));
}

Py::Int PersistancePy::getMemSize(void) const
{
    return Py::Int((long)getPersistanceObject()->getMemSize());
}


PyObject *PersistancePy::getCustomAttributes(const char* attr) const
{
    return 0;
}

int PersistancePy::setCustomAttributes(const char*,PyObject *obj)
{
    return 0; 
}

